import{createPublicKey,verify}from"node:crypto";import{readFileSync}from"node:fs";import{assessPrecommittedValuationMethod,CctPrecommittedValuationMethodRuntime}from"../sequenced-restoration-v7.3-precommitted-valuation-method/runtime.mjs";const SPEC=JSON.parse(readFileSync(new URL("./spec.json",import.meta.url)));
export const crosscheckPayload=x=>[x.schema,x.assessorId,x.controller,x.failureDomain,x.channel,x.valuationMethodDigest,x.measurementRootDigest,x.rawDataRootDigest,x.generatorDigest,x.codeDigest,x.samplingFrameDigest,x.assumptionSetDigest,x.fundingController,JSON.stringify(x.dependencyDisclosures),JSON.stringify(x.estimates)].join("\n");
function valid(x){if(x?.schema!=="cct-rival-valuation-crosscheck/v1"||![x.measurementRootDigest,x.rawDataRootDigest,x.generatorDigest,x.codeDigest,x.samplingFrameDigest,x.assumptionSetDigest].every(d=>/^[0-9a-f]{64}$/.test(d??""))||typeof x.fundingController!=="string"||!x.fundingController||!Array.isArray(x.dependencyDisclosures)||!x.dependencyDisclosures.every(d=>/^[0-9a-f]{64}$/.test(d.digest??"")&&typeof d.materialToConclusion==="boolean")||!Array.isArray(x.estimates))return false;try{const k=createPublicKey({key:Buffer.from(x.publicKeyDer,"base64"),format:"der",type:"spki"});return verify(null,Buffer.from(crosscheckPayload(x)),k,Buffer.from(x.signature,"base64"));}catch{return false;}}
export function assessRivalValuationCrosscheck(args){const prior=assessPrecommittedValuationMethod(args);if(prior.status!=="precommitted_valuation_method_candidate")return prior;if(!prior.repairApplicable)return{status:SPEC.successStatus,repairApplicable:false,failures:[]};const xs=args.valuationCrosschecks;
 if(!Array.isArray(xs)||xs.length!==SPEC.requiredRivals)return{status:"not_established",failures:["rival_valuation_crosschecks_missing"]};
 const shared=new Set(xs[0]?.dependencyDisclosures?.map(d=>d.digest));const materialShared=xs[1]?.dependencyDisclosures?.some(d=>shared.has(d.digest)&&(d.materialToConclusion||xs[0].dependencyDisclosures.find(a=>a.digest===d.digest)?.materialToConclusion));
 if(!xs.every(valid)||xs.some(x=>x.valuationMethodDigest!==prior.valuationMethodDigest)||new Set(xs.map(x=>x.assessorId)).size!==2||new Set(xs.map(x=>x.controller)).size!==2||new Set(xs.map(x=>x.failureDomain)).size!==2||new Set(xs.map(x=>x.channel)).size!==2||["measurementRootDigest","rawDataRootDigest","generatorDigest","codeDigest","samplingFrameDigest","fundingController"].some(k=>new Set(xs.map(x=>x[k])).size!==2)||materialShared)return{status:"not_established",failures:["rival_valuation_independence_invalid"]};
 const methods=new Map(args.valuationMethod.axes.map(x=>[x.axis,x]));for(const loss of args.repairLossLedger.axes){const vals=xs.map(x=>x.estimates.find(e=>e.axis===loss.axis)?.baselineLoss);if(vals.some(v=>!Number.isSafeInteger(v)||v<0))return{status:"not_established",failures:["rival_valuation_axis_missing"]};const bps=Math.abs(vals[0]-vals[1])*10000/Math.max(vals[0],vals[1],1);if(bps>methods.get(loss.axis).toleranceBps)return{status:"not_established",failures:["rival_valuation_disagreement_exceeds_precommitment"]};}
 return{status:SPEC.successStatus,repairApplicable:true,rivalMethods:2,evidenceLevel:"signed_synthetic_rival_measurements",failures:[]};}
export class CctRivalValuationCrosscheckRuntime extends CctPrecommittedValuationMethodRuntime{}
