import test from "node:test";
import assert from "node:assert/strict";

import {
  buildTrackSearchProjection
} from "./track-search-projection.mjs";

test("produit une requête exacte sans modifier la source", () => {
  const input = {
    title: "As We Begin",
    channelTitle: "Pye Corner Audio - Topic",
    description: `
As We Begin · Pye Corner Audio
Main Artist: Pye Corner Audio
Auto-generated by YouTube.
`
  };

  const before = JSON.stringify(input);

  const projection =
    buildTrackSearchProjection(input);

  assert.equal(
    JSON.stringify(input),
    before
  );

  assert.ok(
    projection.queries.some(
      (query) =>
        query.kind === "exact" &&
        query.artist === "Pye Corner Audio" &&
        query.title === "As We Begin"
    )
  );

  assert.equal(
    projection.policy.mutatesRaw,
    false
  );
});

test("génère une variante sans diacritiques sans déclarer un alias", () => {
  const projection =
    buildTrackSearchProjection({
      title: "Nightly Cares",
      channelTitle: "Mum - Topic",
      description: `
Nightly Cares · Múm
Auto-generated by YouTube.
`
    });

  assert.ok(
    projection.queries.some(
      ({ artist }) => artist === "Múm"
    )
  );

  assert.ok(
    projection.queries.some(
      ({ artist }) => artist === "Mum"
    )
  );

  assert.equal(
    projection.policy.normalizationsAreAliases,
    false
  );
});

test("normalise temporairement la ponctuation", () => {
  const projection =
    buildTrackSearchProjection({
      title: "Everything Is Fake",
      channelTitle: "Mr. Oizo - Topic",
      description: `
Everything Is Fake · Mr. Oizo
Auto-generated by YouTube.
`
    });

  assert.ok(
    projection.queries.some(
      ({ artist }) => artist === "Mr. Oizo"
    )
  );

  assert.ok(
    projection.queries.some(
      ({ artist }) => artist === "Mr Oizo"
    )
  );
});

test("la version peut être ajoutée temporairement au titre de recherche", () => {
  const projection =
    buildTrackSearchProjection({
      title: "Freeze (Thomas Schumacher Remix)",
      channelTitle: "Huntemann - Topic",
      description: `
Freeze (Thomas Schumacher Remix) · Huntemann
Main Artist: Huntemann
Remixer: Thomas Schumacher
Auto-generated by YouTube.
`
    });

  assert.equal(
    projection.interpreted.title,
    "Freeze"
  );

  assert.ok(
    projection.queries.some(
      ({ title }) =>
        title ===
        "Freeze Thomas Schumacher Remix"
    )
  );
});

test("les candidats concurrents restent des recherches faibles et non des identités", () => {
  const projection =
    buildTrackSearchProjection({
      title: "Ignition Key (Original Mix)",
      channelTitle: "Kei Hayakawa - Topic",
      description: `
Ignition Key (Original Mix) · Ken Hayakawa
Artist: Ken Hayakawa
Auto-generated by YouTube.
`
    });

  assert.equal(
    projection.interpreted.identityStatus,
    "unresolved"
  );

  assert.ok(
    projection.queries.length > 0
  );

  assert.equal(
    projection.policy.identityResolved,
    false
  );
});

test("une absence de catalogue reste vide et ne devient jamais la chaîne null", () => {
  const projection =
    buildTrackSearchProjection({
      title: "Metal Works (Original Mix)",
      channelTitle: "POLI - Topic",
      description: `
Metal Works (Original Mix) · PØLI
Auto-generated by YouTube.
`
    });

  assert.equal(
    projection.interpreted.catalogueCode,
    null
  );

  assert.ok(
    projection.queries.every(
      ({ catalogueCode }) =>
        catalogueCode !== "null"
    )
  );

  assert.ok(
    !projection.queries.some(
      ({ transformations }) =>
        transformations.includes(
          "catalogue_constraint"
        )
    )
  );
});

test("un conteneur Release - Topic ne pollue pas les requêtes artiste", () => {
  const projection =
    buildTrackSearchProjection({
      title: "BOYÉ - Skefre, Ismayyyel",
      channelTitle: "Release - Topic",
      description: `
BOYÉ - Skefre, Ismayyyel · Skefre
Auto-generated by YouTube.
`
    });

  assert.ok(
    !projection.queries.some(
      ({ artist }) =>
        artist === "Release"
    )
  );

  assert.ok(
    projection.queries.some(
      ({ artist }) =>
        artist === "Skefre"
    )
  );
});

test("une position vinyle devient une variante de recherche sans modifier l'interprétation", () => {
  const projection =
    buildTrackSearchProjection({
      title: "B1. Pye Corner Audio - Island Of Ghosts [AF010]",
      channelTitle: "DMTR // NO Sleep",
      description: ""
    });

  assert.ok(
    projection.queries.some(
      ({ artist, transformations }) =>
        artist === "Pye Corner Audio" &&
        transformations.includes(
          "strip_track_position_prefix"
        )
    )
  );

  assert.ok(
    projection.queries.some(
      ({ artist }) =>
        artist === "B1. Pye Corner Audio"
    )
  );
});
