import test from "node:test";
import assert from "node:assert/strict";

import { resolveTrack } from "./track-resolution.mjs";

test("une chaîne Release - Topic ne devient jamais un artiste", () => {
  const result = resolveTrack({
    title: "BOYÉ - Skefre, Ismayyyel",
    channelTitle: "Release - Topic",
    description: `
BOYÉ - Skefre, Ismayyyel · Skefre
Auto-generated by YouTube.
`
  });

  assert.ok(
    !result.allArtistCandidates.some(
      ({ name }) => name === "Release"
    )
  );
});

test("la métadonnée Topic peut contester la frontière du titre", () => {
  const result = resolveTrack({
    title: "BOYÉ - Skefre, Ismayyyel",
    channelTitle: "Release - Topic",
    description: `
BOYÉ - Skefre, Ismayyyel · Skefre
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.preferredArtists.some(
      ({ name }) => name === "Skefre"
    )
  );

  assert.equal(result.identityStatus, "unresolved");
});

test("un featuring reste secondaire", () => {
  const result = resolveTrack({
    title: "Nieuport Beach Ft. BEN PLG",
    channelTitle: "Absolem - Topic",
    description: `
Nieuport Beach Ft. BEN PLG · ABSOLEM

Main Artist: ABSOLEM
Featured Artist: BEN PLG
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.preferredArtists.some(
      ({ name }) => name === "ABSOLEM"
    )
  );

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "BEN PLG" &&
        role === "featuring"
    )
  );
});

test("une graphie différente ne résout pas une identité canonique", () => {
  const result = resolveTrack({
    title: "Nightly Cares",
    channelTitle: "Mum - Topic",
    description: `
Nightly Cares · Múm
Auto-generated by YouTube.
`
  });

  assert.equal(result.identityStatus, "unresolved");
  assert.ok(result.preferredArtists.length >= 1);
});

test("plusieurs artistes documentés restent visibles", () => {
  const result = resolveTrack({
    title: "Pas lâcher",
    channelTitle: "1863 - Topic",
    description: `
Pas lâcher · 1863

Main Artist: 1863
Artist: Kosei
Artist: La Fève
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.preferredArtists.some(
      ({ name }) => name === "1863"
    )
  );

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "Kosei" &&
        role === "credited"
    )
  );

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "La Fève" &&
        role === "credited"
    )
  );
});

test("un titre Topic contenant un tiret reste un titre et ne fabrique pas un artiste", () => {
  const result = resolveTrack({
    title: "BOYÉ - Skefre, Ismayyyel",
    channelTitle: "Release - Topic",
    description: `
BOYÉ - Skefre, Ismayyyel · Skefre
Auto-generated by YouTube.
`
  });

  assert.equal(
    result.title,
    "BOYÉ - Skefre, Ismayyyel"
  );

  assert.deepEqual(
    result.preferredArtists.map(({ name }) => name),
    ["Skefre"]
  );

  assert.ok(
    !result.allArtistCandidates.some(
      ({ name }) => name === "BOYÉ"
    )
  );
});

test("une collaboration documentée n'est pas signalée comme conflit", () => {
  const result = resolveTrack({
    title: "Comic sans MS",
    channelTitle: "Caballero & JeanJass - Topic",
    description: `
Comic sans MS · Caballero & JeanJass
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.issues.some(
      ({ type, severity }) =>
        type === "documented_collaboration" &&
        severity === "info"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type }) =>
        type === "multiple_primary_candidates"
    )
  );
});

test("PØLI et POLI sont une variante orthographique, pas une identité résolue", () => {
  const result = resolveTrack({
    title: "Metal Works (Original Mix)",
    channelTitle: "POLI - Topic",
    description: `
Metal Works (Original Mix) · PØLI
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.issues.some(
      ({ type }) =>
        type === "orthographic_variant"
    )
  );

  assert.equal(
    result.identityStatus,
    "unresolved"
  );
});

test("The Detroit Experiment et Detroit Experiment restent une variante de crédit", () => {
  const result = resolveTrack({
    title: "Vernors",
    channelTitle: "The Detroit Experiment - Topic",
    description: `
Vernors · Detroit Experiment
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.issues.some(
      ({ type }) =>
        type === "credit_name_variant"
    )
  );

  assert.equal(
    result.identityStatus,
    "unresolved"
  );
});

test("joint A+B avec chaîne Topic A reste une collaboration et non un conflit", () => {
  const result = resolveTrack({
    title: "Robots",
    channelTitle: "Landhouse - Topic",
    description: `
Robots · Landhouse & Raddantze
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.issues.some(
      ({ type }) =>
        type === "documented_collaboration"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type, severity }) =>
        type === "multiple_primary_candidates" &&
        severity === "review"
    )
  );
});

test("un featuring explicite ne reste pas simultanément primary", () => {
  const result = resolveTrack({
    title: "Nieuport Beach Ft. BEN PLG",
    channelTitle: "Absolem - Topic",
    description: `
Nieuport Beach Ft. BEN PLG · ABSOLEM · BEN plg
Main Artist: ABSOLEM
Main Artist: BEN plg
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name.toLocaleLowerCase() === "ben plg" &&
        role === "featuring"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type, candidates = [] }) =>
        type === "multiple_primary_candidates" &&
        candidates.some(
          ({ name }) =>
            name.toLocaleLowerCase() === "ben plg"
        )
    )
  );
});

test("un remixer explicite ne reste pas simultanément primary", () => {
  const result = resolveTrack({
    title: "Raval (Earth Trax Remix)",
    channelTitle: "Wayward - Topic",
    description: `
Raval (Earth Trax Remix) · Earth Trax · Wayward
Producer: Wayward
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "Earth Trax" &&
        role === "remixer"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type, candidates = [] }) =>
        type === "multiple_primary_candidates" &&
        candidates.some(
          ({ name }) => name === "Earth Trax"
        )
    )
  );
});


test("plusieurs Main Artist explicites sont un multi-main documenté, pas un conflit", () => {
  const result = resolveTrack({
    title: "Chloroform",
    channelTitle: "Lucy - Topic",
    description: `
Chloroform · Lucy · Rrose
Main Artist: Lucy
Main Artist: Rrose
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.issues.some(
      ({ type, severity }) =>
        type === "documented_multi_main" &&
        severity === "info"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type, severity }) =>
        type === "multiple_primary_candidates" &&
        severity === "review"
    )
  );
});

test("le nom de chaîne Topic devient un indice secondaire quand le header crédite déjà l'artiste", () => {
  const result = resolveTrack({
    title: "Disco Science",
    channelTitle: "David Gravell - Topic",
    description: `
Disco Science · Mirwais
Composer: Mirwais Ahmadzai
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.preferredArtists.some(
      ({ name }) => name === "Mirwais"
    )
  );

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "David Gravell" &&
        role === "channel_hint"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ type }) =>
        type === "multiple_primary_candidates"
    )
  );
});

test("un Topic DA Uzi n'est pas contredit par le simple nom de chaîne DA", () => {
  const result = resolveTrack({
    title: "Texte noir",
    channelTitle: "DA - Topic",
    description: `
Texte noir · DA Uzi · Agis ou Rêve
Auto-generated by YouTube.
`
  });

  assert.ok(
    result.preferredArtists.some(
      ({ name }) => name === "DA Uzi"
    )
  );

  assert.ok(
    result.secondaryCredits.some(
      ({ name, role }) =>
        name === "DA" &&
        role === "channel_hint"
    )
  );

  assert.ok(
    !result.issues.some(
      ({ severity }) => severity === "review"
    )
  );
});
