import test from "node:test";
import assert from "node:assert/strict";

import {
  collectTrackEvidence,
  inferTrackStructure
} from "./track-evidence.mjs";

test("un Topic sans artiste dans le titre récupère l'artiste via les métadonnées", () => {
  const result = inferTrackStructure({
    id: "topic-1",
    title: "As We Begin",
    channelTitle: "Pye Corner Audio - Topic",
    description: `
As We Begin · Pye Corner Audio · Andy Bell

Main Artist: Pye Corner Audio
Featured Artist: Andy Bell
Auto-generated by YouTube.
`
  });

  assert.equal(result.status, "structured");
  assert.equal(result.title, "As We Begin");

  assert.ok(
    result.artists.some(
      ({ name, role }) =>
        name === "Pye Corner Audio" &&
        role === "primary"
    )
  );

  assert.ok(
    result.artists.some(
      ({ name, role }) =>
        name === "Andy Bell" &&
        role === "featuring"
    )
  );
});

test("un remixer explicite de description est conservé comme rôle", () => {
  const result = inferTrackStructure({
    title: "Freeze (Thomas Schumacher Remix)",
    channelTitle: "Huntemann - Topic",
    description: `
Freeze (Thomas Schumacher Remix) · Huntemann · Thomas Schumacher

Artist: Huntemann
Remixer: Thomas Schumacher
Auto-generated by YouTube.
`
  });

  assert.equal(result.status, "structured");
  assert.equal(result.title, "Freeze");

  assert.ok(
    result.artists.some(
      ({ name, role }) =>
        name === "Huntemann" &&
        role === "primary"
    )
  );

  assert.ok(
    result.artists.some(
      ({ name, role }) =>
        name === "Thomas Schumacher" &&
        role === "remixer"
    )
  );
});

test("la syntaxe du titre et les métadonnées se corroborent sans fusion d'identité", () => {
  const result = inferTrackStructure({
    title:
      "Pye Corner Audio feat. Ian Rankin - The Breath Of Now (Official Video)",
    channelTitle: "Pye Corner Audio",
    description: ""
  });

  assert.equal(result.title, "The Breath Of Now");

  assert.deepEqual(
    result.artists.map(({ name, role }) => [name, role]),
    [
      ["Ian Rankin", "featuring"],
      ["Pye Corner Audio", "primary"]
    ]
  );

  assert.equal(result.identityStatus, "unresolved");
});

test("collectTrackEvidence conserve les sources de provenance", () => {
  const result = collectTrackEvidence({
    title: "Eight Thousand Years",
    channelTitle: "Ancient Methods - Topic",
    description: `
Eight Thousand Years · Ancient Methods

Main Artist: Ancient Methods
Auto-generated by YouTube.
`
  });

  const artist = result.observations.find(
    (item) =>
      item.kind === "artist" &&
      item.value === "Ancient Methods"
  );

  assert.ok(artist);
  assert.ok(
    artist.sources.includes(
      "description_explicit_field"
    )
  );
  assert.ok(
    result.observations.some(
      (item) =>
        item.kind === "artist" &&
        item.value === "Ancient Methods" &&
        item.role === "channel_hint" &&
        item.sources.includes(
          "youtube_topic_channel"
        )
    )
  );

  /*
   * La présence de preuves concordantes ne signifie toujours
   * pas qu'on a résolu une identité Discogs/MusicBrainz.
   */
  assert.equal(result.identityStatus, "unresolved");
});
