import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { discogsReleaseGraph } from '../lib/catalogue.mjs';

// Isolated browser + server. Never uses the user's browser profile or .data.
const { chromium } = await import(process.env.SCOUT_PLAYWRIGHT_MODULE || 'playwright');
const folder = await mkdtemp(join(tmpdir(), 'scout-ui-audit-'));
const probe = createServer(); probe.listen(0, '127.0.0.1'); await once(probe, 'listening');
const port = probe.address().port; await new Promise(resolve => probe.close(resolve));
const server = spawn(process.execPath, ['server.mjs'], { cwd: new URL('../', import.meta.url), env: { ...process.env, PORT: String(port), SCOUT_DATA_FILE: join(folder, 'state.json'), DISCOGS_TOKEN_FILE: join(folder, 'token'), DISCOGS_TOKEN: '' }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
try {
  await Promise.race([once(server.stdout, 'data'), new Promise((_, reject) => setTimeout(() => reject(new Error('Server startup timeout')), 5000))]);
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  // Block all external services in this audit; API checks use dedicated fixtures.
  await page.route('**/*', route => route.request().url().startsWith(`http://localhost:${port}/`) ? route.continue() : route.abort());
  await page.goto(`http://localhost:${port}/`);
  await page.locator('#workspace-empty').waitFor();
  await page.screenshot({ path: join(folder, 'explorer-empty-desktop.png'), fullPage: true });
  assert.deepEqual(errors, []);
  await page.getByRole('button', { name: '＋ Choisir un départ' }).click();
  await page.locator('#seed-dialog[open]').waitFor();
  await page.getByRole('button', { name: 'Fermer le choix du départ' }).click();
  await page.keyboard.press('Control+k');
  await page.locator('#seed-dialog[open]').waitFor();
  assert.equal(await page.locator('#seed-search').evaluate(node => node === document.activeElement), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#seed-dialog').evaluate(node => node.open), false);
  await page.getByRole('link', { name: /Bibliothèque & sources/ }).click();
  await page.locator('#sources-view:not([hidden])').waitFor();
  await page.screenshot({ path: join(folder, 'sources-desktop.png'), fullPage: true });
  await page.getByRole('link', { name: /Carnet/ }).click();
  await page.locator('#notebook-view:not([hidden])').waitFor();
  await page.screenshot({ path: join(folder, 'notebook-empty-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: /Explorer/ }).click();
  await page.screenshot({ path: join(folder, 'explorer-empty-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No mobile horizontal overflow');
  assert.deepEqual(errors, []);
  // Deterministic catalogue, served by the real local graph engine.
  const deltas = Array.from({ length: 15 }, (_, index) => discogsReleaseGraph({ id: 100 + index, title: index ? `Night Routes ${index}` : 'First Light', artists: [{ id: index ? 20 + index : 10, name: index ? `Satellite ${index}` : 'Signal Coast' }], labels: [{ id: 77, name: 'Tidal Records' }], tracklist: [{ title: index ? `Night Routes ${index}` : 'First Light', position: 'A1', type_: 'track' }], year: 2023 }));
  const delta = { entities: deltas.flatMap(item => item.entities), edges: deltas.flatMap(item => item.edges) };
  const imported = await fetch(`http://localhost:${port}/api/graph/ingest`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(delta) });
  assert.equal(imported.status, 200);
  await page.reload();
  await page.getByRole('button', { name: '＋ Choisir un départ' }).click();
  await page.locator('#seed-type').selectOption('artist');
  await page.locator('#seed-search').fill('signal');
  await page.locator('.seed-result').filter({ hasText: 'Signal Coast' }).click();
  await page.locator('#discover-label .derived-card').first().waitFor();
  await page.locator('#workspace-cancel').waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: join(folder, 'explorer-results-desktop.png'), fullPage: true });
  assert.equal(await page.locator('.discovery-group:visible').count(), 1);
  assert.equal(await page.locator('#seed-dialog').evaluate(node => node.open), false);
  const firstTitle = await page.locator('#discover-label .derived-card h3').first().innerText();
  await page.locator('#discover-label [data-keep]').first().click();
  await page.locator('#workspace-pause').click();
  await page.getByRole('button', { name: 'Reprendre cette direction' }).waitFor();
  assert.equal(await page.locator('#discoveries:visible').count(), 0);
  await page.reload();
  await page.getByRole('button', { name: 'Reprendre cette direction' }).waitFor();
  assert.equal(await page.locator('#discoveries:visible').count(), 0, 'Paused state survives reload');
  await page.getByRole('button', { name: 'Reprendre cette direction' }).click();
  await page.locator('#discover-label .derived-card').first().waitFor();
  await page.locator('#discover-label [data-next]').click();
  assert.notEqual(await page.locator('#discover-label .derived-card h3').first().innerText(), firstTitle, 'Reroll changes the selected candidates');
  await page.getByRole('link', { name: /Carnet/ }).click();
  await page.locator('.notebook-card textarea').fill('Une porte vers les autres sorties du label.');
  await page.locator('.notebook-card select').selectOption('listen');
  await page.reload();
  await page.locator('.notebook-card').waitFor();
  assert.equal(await page.locator('.notebook-card textarea').inputValue(), 'Une porte vers les autres sorties du label.');
  await page.locator('#notebook-search').fill('absent-title');
  assert.equal(await page.locator('.notebook-card:visible').count(), 0);
  await page.locator('#notebook-search').fill('');
  await page.locator('#notebook-filter').selectOption('kept');
  assert.equal(await page.locator('.notebook-card:visible').count(), 0);
  await page.locator('#notebook-filter').selectOption('listen');
  await page.locator('.notebook-card textarea').fill('Dernière note avant retrait, à conserver.');
  await page.getByRole('button', { name: 'Retirer du carnet' }).click();
  assert.equal(await page.locator('.notebook-card').count(), 0);
  await page.getByRole('button', { name: 'Annuler', exact: true }).click();
  await page.locator('.notebook-card').waitFor();
  assert.equal(await page.locator('.notebook-card textarea').inputValue(), 'Dernière note avant retrait, à conserver.');
  const download = page.waitForEvent('download');
  await page.locator('#export-notebook').click();
  assert.match((await download).suggestedFilename(), /carnet.*json/);
  await page.getByRole('link', { name: /Explorer/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(folder, 'explorer-results-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No results overflow on mobile');
  assert.deepEqual(errors, []);
  // Continue and back must restore the previous candidates, not re-roll them.
  await page.locator('#discover-label [data-continue]').first().click();
  await page.locator('#active-seed h3').filter({ hasText: /Night Routes/ }).waitFor();
  await page.getByRole('button', { name: '← Départ précédent' }).click();
  await page.locator('#active-seed h3').filter({ hasText: 'Signal Coast' }).waitFor();
  await page.locator('#discover-label .derived-card').first().waitFor();
  // One failing direction must not discard the working label catalogue.
  const branchCalls = [];
  let delayAlias = false;
  await page.route('**/api/music/branch?**', async route => {
    const direction = new URL(route.request().url()).searchParams.get('direction'); branchCalls.push(direction);
    if (direction === 'remix') return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Catalogue de test temporairement indisponible' }) });
    if (direction === 'alias' && delayAlias) { await new Promise(resolve => setTimeout(resolve, 1200)); return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ candidates: [], coverage: { complete: true } }) }).catch(() => {}); }
    return route.continue();
  });
  await page.locator('#direction-tab-remix').click();
  await page.locator('#direction-tab-remix[data-state=error]').waitFor();
  const beforeRetry = branchCalls.length;
  await page.getByRole('button', { name: 'Réessayer cette direction', exact: true }).click();
  await page.locator('#direction-tab-remix[data-state=error]').waitFor();
  assert.deepEqual(branchCalls.slice(beforeRetry), ['remix'], 'Retry touches only the requested direction');
  await page.locator('#direction-tab-label').click();
  await page.locator('#discover-label .derived-card').first().waitFor();
  delayAlias = true;
  await page.locator('#direction-tab-alias').click();
  await page.locator('#workspace-cancel').click();
  await page.locator('#workspace-cancel').waitFor({ state: 'hidden' });
  await page.locator('#direction-tab-label').click();
  await page.locator('#discover-label .derived-card').first().waitFor();

  // Full browser import through mocked YouTube responses: duplicates, details,
  // local ID persistence, backup/restore and nonconfigured platform comparisons.
  await page.getByRole('link', { name: /Bibliothèque & sources/ }).click();
  await page.locator('#client-id').fill('123-audit.apps.googleusercontent.com');
  await page.locator('#save-client-id').click();
  await page.locator('#api-key').fill('fixture-api-key-not-a-secret');
  await page.locator('#api-key').dispatchEvent('change');
  await page.unroute('**/*');
  await page.route('**/*', async route => {
    const url = new URL(route.request().url());
    if (url.hostname === 'www.googleapis.com') {
      let body;
      if (url.pathname.endsWith('/playlists')) body = { items: [{ id: 'PLaudit123', snippet: { title: 'Audit collection' }, contentDetails: { itemCount: 4 }, status: { privacyStatus: 'public' } }] };
      else if (url.pathname.endsWith('/playlistItems')) body = { items: ['audit000001', 'audit000002', 'audit000003', 'audit000001'].map(id => ({ contentDetails: { videoId: id }, snippet: { title: `Signal Coast - ${id}`, resourceId: { videoId: id }, publishedAt: '2022-01-01T00:00:00Z' } })) };
      else if (url.pathname.endsWith('/videos')) body = { items: ['audit000001', 'audit000002', 'audit000003'].map(id => ({ id, snippet: { title: `Signal Coast - ${id}`, channelTitle: 'Audit Records', channelId: 'audit-channel', categoryId: '10', publishedAt: '2022-01-01T00:00:00Z' }, contentDetails: { duration: 'PT4M' }, statistics: { viewCount: '100' }, status: { privacyStatus: 'public' } })) };
      else if (url.pathname.endsWith('/search') || url.pathname.endsWith('/i18nRegions')) body = { items: [] };
      else throw new Error(`Unhandled fixture ${url.pathname}`);
      return route.fulfill({ contentType: 'application/json', body: JSON.stringify(body) });
    }
    return url.origin === `http://localhost:${port}` ? route.continue() : route.abort();
  });
  await page.locator('#playlist-links > summary').click();
  await page.locator('#playlist-urls').fill('https://www.youtube.com/playlist?list=PLaudit123');
  await page.locator('#inspect-urls').click();
  await page.locator('#playlist-picker:not([hidden])').waitFor();
  await page.locator('#import-playlists').click();
  await page.waitForFunction(() => document.querySelector('#library-count').textContent.startsWith('3 vidéos'));
  await page.reload();
  assert.equal(await page.locator('#client-id').inputValue(), '123-audit.apps.googleusercontent.com');
  await page.waitForFunction(() => document.querySelector('#library-count').textContent.startsWith('3 vidéos'));
  await page.locator('#backup-settings > summary').click();
  const exported = page.waitForEvent('download'); await page.locator('#export-backup').click();
  const backup = await exported; const backupPath = join(folder, 'backup-fixture.json'); await backup.saveAs(backupPath);
  const backupText = await readFile(backupPath, 'utf8');
  assert.equal(backupText.includes('fixture-api-key'), false);
  assert.equal(backupText.includes('123-audit.apps'), false);
  await page.locator('#restore-backup').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"format":"wrong"}') });
  await page.waitForFunction(() => document.querySelector('#backup-status').classList.contains('error'));
  assert.match(await page.locator('#library-count').innerText(), /3 vidéos/);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#restore-backup').setInputFiles(backupPath);
  await page.waitForFunction(() => !document.querySelector('#restore-backup').disabled);
  assert.match(await page.locator('#library-count').innerText(), /3 vidéos/);
  assert.equal(await page.locator('#client-id').inputValue(), '123-audit.apps.googleusercontent.com');
  await page.locator('#catalogue-tools > summary').click();
  await page.locator('#bandcamp-import').setInputFiles({ name: 'bandcamp.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ sourceUrl: 'https://audit-fixture.bandcamp.com/album/test', artist: 'Audit Artist', title: 'Browser import', tracks: [{ title: 'First Step' }] })) });
  await page.waitForFunction(() => document.querySelector('#bandcamp-import-status').textContent.includes('enregistrée'));
  await page.locator('#bandcamp-url').fill('https://audit-fixture.bandcamp.com/album/manual');
  await page.locator('#bandcamp-artist').fill('Another Audit Artist');
  await page.locator('#bandcamp-title').fill('Form without JSON');
  await page.locator('#bandcamp-tracks').fill('Track One\nTrack Two');
  await page.locator('#bandcamp-entry-form button').click();
  await page.waitForFunction(() => document.querySelector('#bandcamp-import-status').textContent.includes('Form without JSON') && document.querySelector('#bandcamp-import-status').textContent.includes('enregistrée'));
  await page.locator('#platform-isrc').fill('FRABC2600001');
  await page.locator('#platform-compare-submit').click();
  await page.waitForFunction(() => document.querySelector('#platform-compare-results').textContent.includes('configuré'));
  await page.screenshot({ path: join(folder, 'sources-mobile.png'), fullPage: true });
  const overflows = await page.evaluate(() => [...document.querySelectorAll('#sources-view *')].filter(node => node.getBoundingClientRect().width && node.getBoundingClientRect().right > innerWidth + 1).map(node => `${node.tagName}#${node.id}.${node.className}`));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `No source controls overflow: ${overflows.join(', ')}`);
  await page.getByRole('link', { name: /Explorer/ }).click();
  await page.getByRole('button', { name: /＋ Changer de départ/ }).click();
  await page.locator('#seed-type').selectOption('track');
  await page.locator('#seed-search').fill('audit000');
  assert.equal(await page.locator('.seed-result').count(), 3);
  await page.locator('#suggestion-picker > summary').click();
  await page.locator('#compose').click();
  await page.locator('#videos .video-card').first().waitFor();
  await page.getByRole('button', { name: 'Fermer le choix du départ' }).click();
  await page.locator('.workspace-session-actions > summary').click();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#clear-exploration').click();
  await page.locator('#workspace-empty:not([hidden])').waitFor();
  await page.reload();
  await page.locator('#workspace-empty:not([hidden])').waitFor();
  assert.deepEqual(errors, []);
  const checks = ['empty-state', 'seed-dialog', 'three-views', 'mobile-empty', 'local-artist-search', 'local-graph-results', 'one-visible-direction', 'keep', 'pause-resume', 'reroll', 'notebook-note', 'notebook-status', 'reload-persistence', 'notebook-search', 'notebook-filter', 'remove-undo', 'notebook-export', 'mobile-results', 'continue-back', 'single-direction-retry', 'cancel', 'playlist-import-deduplication', 'oauth-id-persistence', 'backup-no-secrets', 'invalid-backup-rejected', 'restore-backup', 'bandcamp-json-import', 'bandcamp-form', 'unconfigured-platforms', 'mobile-sources', 'imported-seed-search', 'programme-suggestions', 'close-session-reload', 'no-page-errors', 'keyboard-dialog', 'pause-reload'];
  await writeFile(join(folder, 'audit.json'), JSON.stringify({ checks, errors, fixtureOnly: true }, null, 2));
  console.log(JSON.stringify({ status: 'passed', folder, checks: checks.length, fixtureOnly: true }));
} finally { try { await browser?.close(); } finally { server.kill('SIGTERM'); } }
