import test from "node:test"; import assert from "node:assert/strict";
import { assessEquivocationBoundedRevocation, CctEquivocationBoundedRevocationRuntime, verifyObserverEquivocation } from "./runtime.mjs";
import { audit, axes, completeExercise, differentTickEvidence, equivocationEvidence, initialCheckpointMemory, mereAbsenceEvidence, selectorRegistry, transitionFixture, validAmendment, validEndorsements, validValidation } from "./fixtures.mjs";
function setup() { const validation = validValidation(); const memory = initialCheckpointMemory(validation); const transition = transitionFixture(memory, true); const selectors = selectorRegistry(); const endorsements = validEndorsements(transition); return { validation, memory, transition, selectors, endorsements }; }
function assess(s, evidence) { return assessEquivocationBoundedRevocation(axes, audit, completeExercise(), validAmendment(), s.validation, s.memory, s.transition, s.selectors, s.endorsements, evidence); }
test("permits revocation only for two incompatible signatures at the same position", () => { const s = setup(); const evidence = equivocationEvidence(s.memory); assert.equal(verifyObserverEquivocation(evidence, s.transition.newRegistry), true); assert.equal(assess(s, evidence).revocableObserverId, "observer-c"); });
test("refuses to turn absence or normal checkpoint advance into fault", () => { const s = setup(); for (const evidence of [mereAbsenceEvidence(s.memory), differentTickEvidence(s.memory)]) assert.deepEqual(assess(s, evidence).failures, ["observer_equivocation_not_proven"]); });
test("refuses evidence against an observer outside the active registry", () => { const s = setup(); const altered = { ...s, transition: { ...s.transition, newRegistry: s.transition.newRegistry.filter((x) => x.observerId !== "observer-c") } }; assert.equal(assess(altered, equivocationEvidence(s.memory)).status, "not_established"); });
test("runtime blocks revocation without cryptographic fault evidence", () => { const runtime = new CctEquivocationBoundedRevocationRuntime(); runtime.state.phase = "staged_restoration_receipt_pending"; runtime.state.debts = axes.map((axis) => ({ axis, status: "open" })); assert.throws(() => runtime.decide({ view: { cct: { tick: 28 } }, allowedActions: ["revoke"] }), { message: /CCT_OBSERVER_EQUIVOCATION_UNPROVEN/ }); });
