import test from "node:test"; import assert from "node:assert/strict";
import { assessIndependentSuspensionAdjudication, CctIndependentSuspensionAdjudicationRuntime } from "./runtime.mjs";
import { adjudicationFixture, adjudicationVotes, adjudicatorRegistry, audit, axes, completeExercise, initialCheckpointMemory, selectorRegistry, suspensionEndorsements, suspensionFixture, transitionFixture, validAmendment, validEndorsements, validValidation } from "./fixtures.mjs";
function setup() { const validation = validValidation(); const memory = initialCheckpointMemory(validation); const transition = transitionFixture(memory, true); const selectors = selectorRegistry(); const suspension = suspensionFixture(transition, validation); return { validation, memory, transition, selectors, suspension, admission: validEndorsements(transition), suspensionVotes: suspensionEndorsements(suspension, selectors), adjudicators: adjudicatorRegistry() }; }
function assess(s, decision, votes = adjudicationVotes(decision)) { return assessIndependentSuspensionAdjudication(axes, audit, completeExercise(), validAmendment(), s.validation, s.memory, s.transition, s.selectors, s.admission, s.suspension, s.suspensionVotes, [], s.adjudicators, decision, votes); }
test("restores immediately and requires correction plus repair when allegation is not established", () => { const s = setup(); const d = adjudicationFixture(s.suspension); const r = assess(s, d); assert.equal(r.status, "independent_suspension_adjudication_candidate"); assert.equal(r.restoreAtTick, d.decidedAtTick); assert.equal(r.repairRequired, true); assert.equal(r.automaticRevocation, false); });
test("adds selector accountability when the suspension was abusive", () => { const s = setup(); const r = assess(s, adjudicationFixture(s.suspension, "suspension-abusive")); assert.equal(r.selectorAccountabilityRequired, true); });
test("a substantiated safeguard runs only to the original expiry and cannot revoke automatically", () => { const s = setup(); const r = assess(s, adjudicationFixture(s.suspension, "safeguard-substantiated")); assert.equal(r.restoreAtTick, s.suspension.endsAtTick); assert.equal(r.automaticRevocation, false); });
test("refuses self-adjudication by a selector", () => { const s = setup(); const bad = s.adjudicators.map((x, i) => i === 0 ? { ...x, controller: s.selectors[0].controller } : x); const d = adjudicationFixture(s.suspension); assert.equal(assessIndependentSuspensionAdjudication(axes, audit, completeExercise(), validAmendment(), s.validation, s.memory, s.transition, s.selectors, s.admission, s.suspension, s.suspensionVotes, [], bad, d, adjudicationVotes(d)).status, "not_established"); });
test("refuses exoneration without a repair receipt", () => { const s = setup(); const d = adjudicationFixture(s.suspension, "allegation-not-established", { repairReceipt: "" }); assert.deepEqual(assess(s, d).failures, ["finding_consequence_mismatch"]); });
test("runtime blocks missing adjudication", () => { const runtime = new CctIndependentSuspensionAdjudicationRuntime(); runtime.state.phase = "staged_restoration_receipt_pending"; runtime.state.debts = axes.map((axis) => ({ axis, status: "open" })); assert.throws(() => runtime.decide({ view: { cct: { tick: 33 } }, allowedActions: ["adjudicate"] }), { message: /CCT_INDEPENDENT_SUSPENSION_ADJUDICATION_UNESTABLISHED/ }); });
