'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const source=fs.readFileSync(__dirname+'/portal/app.js','utf8');
const moduleSource=source.slice(source.indexOf('// Sous-agents natifs :'),source.indexOf('// Fin du module sous-agents.'));
function harness(overrides={}){
 let focus;
 class Node{
  constructor(tag,text,cls){Object.assign(this,{tagName:tag.toUpperCase(),ownText:text??'',className:cls||'',children:[],dataset:{},attrs:{},style:{},scrollTop:0,scrollHeight:1000,clientHeight:300,hidden:false});this.classList={contains:name=>this.className.split(' ').includes(name),add:(...names)=>{for(const n of names)if(!this.classList.contains(n))this.className+=' '+n;},remove:(...names)=>{this.className=this.className.split(' ').filter(n=>!names.includes(n)).join(' ');},toggle:(name,state)=>{if(state??!this.classList.contains(name))this.classList.add(name);else this.classList.remove(name);}};}
  get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}set textContent(value){this.ownText=String(value);this.children=[];}
  get isConnected(){return this===body||!!this.parentNode?.isConnected;}
  append(...nodes){for(const n of nodes){n.remove();n.parentNode=this;this.children.push(n);}}
  prepend(...nodes){for(const n of nodes.reverse()){n.remove();n.parentNode=this;this.children.unshift(n);}}
  before(node){const parent=this.parentNode;if(!parent)return;node.remove();node.parentNode=parent;parent.children.splice(parent.children.indexOf(this),0,node);}
  replaceChildren(...nodes){for(const n of this.children)n.parentNode=null;this.children=[];this.ownText='';this.append(...nodes);}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(n=>n!==this);this.parentNode=null;}
  setAttribute(key,value){this.attrs[key]=String(value);}getAttribute(key){return this.attrs[key];}
  focus(){focus=this;}click(){return this.onclick?.();}addEventListener(){}
  matches(selector){const id=selector.match(/^#([\w-]+)/);if(id&&this.id!==id[1])return false;const tag=selector.match(/^([a-z][a-z0-9]*)/i);if(tag&&this.tagName!==tag[1].toUpperCase())return false;for(const name of selector.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(name[1]))return false;for(const attr of selector.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)){let value;if(attr[1]==='open')value=this.open?true:undefined;else if(attr[1].startsWith('data-'))value=this.dataset[attr[1].slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())];else value=this.attrs[attr[1]];if(value===undefined||attr[2]!==undefined&&String(value)!==attr[2])return false;}return true;}
  querySelectorAll(selector){return this.children.flatMap(n=>[...(n.matches(selector)?[n]:[]),...n.querySelectorAll(selector)]);}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  closest(selector){for(let n=this;n;n=n.parentNode)if(n.matches(selector))return n;return null;}
 }
 const body=new Node('body'),main=new Node('main');body.append(main);
 const document={body,createTextNode:text=>new Node('#text',text),getElementById:id=>body.querySelector('#'+id),querySelector:selector=>body.querySelector(selector),querySelectorAll:selector=>body.querySelectorAll(selector)};
 const requests=[],fileCalls=[],state={id:'parent',draft:'Texte conservé',queue:[{text:'En attente'}],messages:[]};
 const context={document,$:id=>document.getElementById(id),el:(...args)=>new Node(...args),Date,URL,AbortSignal,nativeCurrent:'parent',nativeState:()=>state,chatProject:()=>'/parent',executionDuration:ms=>Math.round(ms/1000)+'s',toolActivity:p=>p.tool,localApiError:code=>Error('HTTP '+code),status(){},setInterval(){},MutationObserver:class{observe(){}},sharedBrowserCleanup:null,parallelChats:new Map(),fetchJSON:async(path,options)=>{requests.push({path,options});return path.endsWith('/children')?[]:path==='/permission'?[]:{};},fetch:async()=>({ok:true,json:async()=>[],headers:{get:()=>null}}),documentCard:(file,id,dir)=>{const card=new Node('div'),button=new Node('button');button.onclick=()=>fileCalls.push({file,id,dir});card.append(button);return card;},...overrides};
 vm.createContext(context);
 const textSource=source.slice(source.indexOf('function nativeWebHref('),source.indexOf('function localDataBlob('));
 vm.runInContext(textSource+'\n'+moduleSource+'\nthis.api={subagentState,subagentGroup,subagentsBusy,refreshSubagents,createSubagentSummary,renderSubagentSurfaces,renderPermissionRequests,replyNativePermission,renderSubagentsPanel,subagentEvents,appendSubagentText,subagentClock,activateRightPanel,closeRightPanel,syncRightPanels};',context);
 const add=(id,tag='section')=>{const node=new Node(tag);node.id=id;main.append(node);return node;};
 return {context,api:context.api,Node,body,main,document,add,requests,fileCalls,state,get focus(){return focus;}};
}
function fixture(h,id,state='running'){
 const group=h.api.subagentGroup('parent'),session={id,parentID:'parent',directory:'/child-project',title:id,time:{created:1000,updated:2000}};group.children.push(session);group.records.set(id,{session,title:id,state,activity:state,model:'qwen3.6-35b-a3b-ud-q4-k-m',start:1000,end:state==='completed'?2000:null,messages:[],revision:1});group.ready=true;group.parentState=h.state;return group;
}
test('summary and list separate active/completed children, retain titles and fixed finished durations',()=>{
 const h=harness(),group=fixture(h,'alpha');fixture(h,'beta','completed');const summary=h.api.createSubagentSummary('parent');assert.match(summary.textContent,/1 en cours.*1 terminé/);assert.equal(summary.querySelectorAll('.subagent-avatar').length,2);
 const panel=h.add('corpus-subagents');panel.dataset.parentId='parent';h.api.renderSubagentsPanel(group,panel);assert.match(panel.textContent,/Actifs · 1/);assert.match(panel.textContent,/Terminés · 1/);assert.equal(panel.querySelectorAll('.subagent-row').length,2);assert.equal(h.api.subagentClock(group.records.get('beta')).textContent,'1s');
});
test('opening and returning from child details preserve parent state and separate list scroll position',()=>{
 const h=harness(),group=fixture(h,'alpha'),panel=h.add('corpus-subagents');panel.dataset.parentId='parent';h.api.renderSubagentsPanel(group,panel);panel.querySelector('.subagents-body').scrollTop=220;panel.querySelector('.subagent-row').click();assert.equal(group.selected,'alpha');assert.equal(h.context.nativeCurrent,'parent');assert.equal(h.state.draft,'Texte conservé');assert.equal(h.state.queue.length,1);assert.match(panel.textContent,/Qwen 3.6 35B · local/);panel.querySelector('.subagents-body').scrollTop=650;panel.querySelector('[aria-label="Retour à la liste des sous-agents"]').click();assert.equal(group.selected,null);assert.equal(panel.querySelector('.subagents-body').scrollTop,220);assert.equal(h.focus,panel.querySelector('.subagent-row'));
});
test('unchanged visible child data preserves mounted DOM despite polling and large cached histories',()=>{
 const h=harness(),group=fixture(h,'alpha','completed'),panel=h.add('corpus-subagents');group.records.get('alpha').messages=Array.from({length:500},(_,i)=>({info:{id:'m'+i},parts:[{type:'text',text:'x'.repeat(2000)}]}));h.api.renderSubagentsPanel(group,panel);const row=panel.querySelector('.subagent-row'),body=panel.querySelector('.subagents-body');group.records.get('alpha').irrelevant='changed';h.api.renderSubagentsPanel(group,panel);assert.equal(panel.querySelector('.subagent-row'),row);assert.equal(panel.querySelector('.subagents-body'),body);assert.ok(panel.dataset.signature.length<1000,'The render signature does not serialize every historical message');
});
test('safe Markdown renders headings, lists, code and local/web links while keeping untrusted HTML inert',()=>{
 const h=harness(),body=new h.Node('section'),record=fixture(h,'child').records.get('child');h.api.appendSubagentText(body,'# Résultat\n\n- **Validé** [source](https://example.org/x)\n- [Fichier](/child-project/a.md:4)\n\n```html\n<img src=x onerror=alert(1)>\n```\n\n[Interdit](javascript:alert(1)) <script>alert(1)</script>',record);assert.equal(body.querySelectorAll('h2').length,1);assert.equal(body.querySelectorAll('li').length,2);assert.equal(body.querySelectorAll('strong').length,1);const link=body.querySelector('a');assert.equal(link.href,'https://example.org/x');assert.equal(link.rel,'noopener noreferrer');assert.equal(body.querySelectorAll('img').length,0);assert.equal(body.querySelectorAll('script').length,0);body.querySelector('.subagent-file-link').click();assert.deepEqual(JSON.parse(JSON.stringify(h.fileCalls)),[{file:{filename:'Fichier',path:'/child-project/a.md'},id:'child',dir:'/child-project'}]);
});
test('reused agents retain separate turn times and tool events without rendering private reasoning',()=>{
 const h=harness(),record=fixture(h,'child').records.get('child');record.messages=[{info:{id:'u1',role:'user',time:{created:1000}},parts:[]},{info:{id:'a1',role:'assistant',finish:'stop',time:{created:1500,completed:2000}},parts:[{id:'r',type:'reasoning',text:'PRIVATE'},{id:'t',type:'text',text:'Old result'}]},{info:{id:'u2',role:'user',time:{created:3000}},parts:[]},{info:{id:'a2',role:'assistant',time:{created:3500}},parts:[{id:'tool',type:'tool',tool:'read',state:{status:'running',input:{filePath:'a.md'}}}]}];const events=h.api.subagentEvents(record,[]),turns=events.filter(e=>e.kind==='turn');assert.equal(turns.length,2);assert.equal(turns[0].end,2000);assert.equal(turns[1].end,null);assert.equal(turns[1].state,'running');assert.doesNotMatch(JSON.stringify(events),/PRIVATE/);assert.equal(events.filter(e=>e.kind==='tools').length,1);
});
test('native approvals require explicit once/reject, preserve family routing and prevent double replies',async()=>{
 let release;const h=harness({fetchJSON:async(path,options)=>{h.requests.push({path,options});await new Promise(resolve=>release=resolve);}}),group=fixture(h,'child');group.permissions=[{id:'parent-ask',sessionID:'parent',permission:'bash'},{id:'child-ask',sessionID:'child',permission:'edit',patterns:['a.md']}];assert.equal(h.api.subagentsBusy('parent'),true);const box=new h.Node('section');h.api.renderPermissionRequests(box,group,group.permissions);assert.match(box.textContent,/Corpus · Approbation/);assert.match(box.textContent,/child · Approbation/);assert.equal(h.requests.length,0);const pending=h.api.replyNativePermission('parent','child-ask','once');await h.api.replyNativePermission('parent','child-ask','once');await h.api.replyNativePermission('parent','parent-ask','always');await h.api.replyNativePermission('parent','unrelated','reject');assert.equal(h.requests.length,1);assert.equal(h.requests[0].path,'/permission/child-ask/reply');assert.equal(h.requests[0].options.headers['x-opencode-directory'],'/child-project');assert.equal(h.requests[0].options.body,'{"reply":"once"}');release();await pending;assert.equal(group.permissions.length,1);assert.equal(group.permissions[0].id,'parent-ask');
});
test('rejected approval transport remains visible and retryable rather than silently granting',async()=>{
 const h=harness({fetchJSON:async()=>{throw Error('503 unavailable');}}),group=fixture(h,'child');group.permissions=[{id:'ask',sessionID:'child',permission:'bash'}];await h.api.replyNativePermission('parent','ask','reject');assert.equal(group.permissions.length,1);assert.equal(group.pendingReplies.size,0);const box=new h.Node('section');h.api.renderPermissionRequests(box,group,group.permissions);assert.match(box.textContent,/503 unavailable/);assert.equal(box.querySelector('button').disabled,false);
});
test('exclusive right tabs retain browser DOM and draft, and closing a child panel never aborts its worker',()=>{
 const h=harness(),browser=h.add('shared-browser'),input=new h.Node('input');input.value='https://example.org/kept';browser.append(input);const panel=h.add('corpus-subagents');h.api.activateRightPanel('corpus-subagents');assert.equal(browser.classList.contains('corpus-inactive-panel'),true);assert.equal(panel.classList.contains('corpus-active-panel'),true);assert.equal(panel.querySelectorAll('.right-panel-tab').length,2);h.api.activateRightPanel('shared-browser');assert.equal(browser.querySelector('input'),input);assert.equal(input.value,'https://example.org/kept');assert.equal(panel.classList.contains('corpus-inactive-panel'),true);h.api.closeRightPanel('corpus-subagents');assert.equal(h.document.getElementById('corpus-subagents'),null);assert.equal(h.document.getElementById('shared-browser'),browser);assert.equal(h.requests.length,0);assert.equal(h.state.draft,'Texte conservé');
});
test('late results from an old parent do not repaint the active family pane or approvals',()=>{
 const h=harness(),group=fixture(h,'child'),panel=h.add('corpus-subagents');panel.dataset.parentId='new-parent';panel.textContent='New conversation';h.context.nativeCurrent='new-parent';h.api.renderSubagentSurfaces(group);assert.equal(panel.textContent,'New conversation');assert.equal(h.document.getElementById('native-permissions'),null);
});
test('refresh calls share a pending promise and enforce a 1500ms read throttle',async()=>{
 let release;const h=harness({fetchJSON:async path=>{h.requests.push(path);if(path.endsWith('/children'))return new Promise(resolve=>release=resolve);return [];}});const one=h.api.refreshSubagents(h.state,{}),two=h.api.refreshSubagents(h.state,{});assert.equal(one,two);assert.equal(h.requests.length,2);release([]);await one;await h.api.refreshSubagents(h.state,{});assert.equal(h.requests.length,2);
});

test('a fresh native abort remains cancelled even when the parent task reports its aborted worker as an error',()=>{
 const h=harness(),group=fixture(h,'child'),record=group.records.get('child'),messages=[{info:{id:'user',role:'user',time:{created:3000}},parts:[]},{info:{id:'reply',role:'assistant',time:{created:3500,completed:4000},error:{name:'AbortedError',data:{message:'Interrupted'}}},parts:[]}],parentMessages=[{parts:[{id:'task',type:'tool',tool:'task',state:{status:'error',time:{start:3000,end:4100},metadata:{sessionId:'child'},error:'Worker failed'}}]}];assert.equal(h.api.subagentState(record.session,messages,{},[],parentMessages).state,'cancelled');
});
test('keyboard arrows and Home/End switch existing tabs and focus the active tab without losing its content',()=>{
 const h=harness(),browser=h.add('shared-browser'),panel=h.add('corpus-subagents');browser.append(new h.Node('p','Browser remains'));h.api.activateRightPanel('shared-browser');let prevented=0;browser.querySelector('.right-panel-tabs').onkeydown({key:'ArrowRight',preventDefault(){prevented++;}});assert.equal(h.body.dataset.activeRightPanel,'corpus-subagents');assert.equal(h.focus.getAttribute('aria-pressed'),'true');panel.querySelector('.right-panel-tabs').onkeydown({key:'Home',preventDefault(){prevented++;}});assert.equal(h.body.dataset.activeRightPanel,'shared-browser');assert.match(browser.textContent,/Browser remains/);assert.equal(prevented,2);
});
