'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {harness}=require('./frontend_test_dom.cjs');
function menuHarness(overrides={}){const h=harness(overrides);h.load('installCompactMenuKeyboard','footerMenuItems','openFooterMenu','installFooterMenus','openBranchMenu');return h;}
function footer(h){const f=h.add('footer','footer',h.body),settings=h.add('old-settings','button',f);settings.setAttribute('data-panel','settings');const row=h.add('row','div',f,'profile-row');row.append(new h.Node('span','Olivier'),new h.Node('button','Mode vocal'));h.ctx.installFooterMenus();return f;}
test('footer is installed once with a single profile entry, voice settings and help',()=>{const h=menuHarness(),f=footer(h);h.ctx.installFooterMenus();assert.equal(f.querySelectorAll('button').length,3);assert.equal(h.document.getElementById('old-settings'),null);h.document.getElementById('footer-voice-button').click();assert.deepEqual(h.calls,[['settings','voice']]);});
test('profile menu is truthful, toggles, resets aria on removal and closes before opening settings',async()=>{const h=menuHarness();footer(h);const button=h.document.getElementById('footer-profile-button');button.click();let menu=h.document.getElementById('corpus-footer-menu');assert.match(menu.textContent,/Profil local/);assert.doesNotMatch(menu.textContent,/Se déconnecter|Pro ·|Inviter|% restant/);assert.equal(button.getAttribute('aria-expanded'),'true');menu.remove();assert.equal(button.getAttribute('aria-expanded'),'false');button.click();menu=h.document.getElementById('corpus-footer-menu');await menu.querySelectorAll('button').find(node=>node.textContent==='Paramètres').click();assert.equal(menu.isConnected,false);assert.deepEqual(h.calls,[['settings','general']]);button.click();button.click();assert.equal(h.document.getElementById('corpus-footer-menu'),null);});
test('compact menu keyboard skips disabled rows and closes on Tab',()=>{const h=menuHarness(),anchor=h.add('anchor','button'),menu=h.add('menu');const one=new h.Node('button','One'),disabled=new h.Node('button','No'),two=new h.Node('button','Two');disabled.disabled=true;menu.append(one,disabled,two);h.ctx.installCompactMenuKeyboard(menu,anchor,{closeOnTab:true});one.focus();menu.onkeydown({key:'ArrowDown',preventDefault(){}});assert.equal(h.focus,two);menu.onkeydown({key:'Home',preventDefault(){}});assert.equal(h.focus,one);menu.onkeydown({key:'Tab'});assert.equal(menu.isConnected,false);assert.equal(h.focus,anchor);});
function branches(overrides={}){const calls=[];const h=menuHarness({chatAction:async value=>{calls.push(value);return value.action==='branches'?{branches:['feature','main','Alpha'],files:[]}:{branch:'main',changes:'M  staged.txt\n?? new.txt\n'};},...overrides});h.branchCalls=calls;h.anchor=h.add('branch','button');return h;}
test('branch menu searches and current selection only dismisses without Git mutation',async()=>{const h=branches();await h.ctx.openBranchMenu('parent',h.anchor);const menu=h.body.querySelector('.branch-menu');assert.match(menu.textContent,/2 éléments non validés/);const search=menu.querySelector('input');search.value='ALP';search.oninput();assert.equal(menu.querySelectorAll('.branch-menu-row').length,1);assert.match(menu.querySelector('.branch-menu-row').textContent,/Alpha/);search.value='';search.oninput();menu.querySelector('[aria-pressed="true"]').click();assert.equal(menu.isConnected,false);assert.equal(h.branchCalls.length,2);assert.equal(h.anchor.getAttribute('aria-expanded'),'false');});
test('branch action closes before confirmation and navigation while confirming prevents mutation',async()=>{let release;const h=branches({corpusConfirm:()=>new Promise(resolve=>release=resolve)});await h.ctx.openBranchMenu('parent',h.anchor);const menu=h.body.querySelector('.branch-menu'),other=menu.querySelectorAll('.branch-menu-row').find(node=>node.textContent==='feature');other.click();other.click();assert.equal(menu.isConnected,false);h.ctx.nativeCurrent='other';release(true);await new Promise(setImmediate);assert.equal(h.branchCalls.length,2);assert.match(h.calls.at(-1)[1],/conversation a changé/);});
test('late branch reads do not reopen a dismissed menu or modify another session',async()=>{const resolves=[];const h=branches({chatAction:()=>new Promise(r=>resolves.push(r))}),work=h.ctx.openBranchMenu('parent',h.anchor);h.body.querySelector('.branch-menu').remove();h.ctx.nativeCurrent='other';resolves[0]({branches:['main']});resolves[1]({branch:'main'});await work;assert.equal(h.body.querySelector('.branch-menu'),null);assert.equal(h.calls.length,0);});
test('Git failure leaves loaded attachment sources visible in the summary',async()=>{const h=harness({chatAction:async()=>{throw Error('Git offline');},chatSnapshot:async()=>({messages:[]}),createSubagentSummary:()=>new h.Node('section','Sous-agents'),sourcesAddHeader:()=>new h.Node('div','Sources'),conversationAttachmentEntries:()=>[{file:{filename:'reference.pdf'}}],openConversationSources(){}});h.add('workspace','section',h.main,'workspace');h.run('const parallelChats=new Map(),parallelStartRequests=new Map();');h.load('createParallelChatSummary','paintParallelChatSummary','showChatSummary');await h.ctx.showChatSummary('parent');const card=h.document.getElementById('chat-summary');assert.match(card.textContent,/Git : Git offline/);assert.match(card.textContent,/reference.pdf/);assert.match(card.textContent,/Chats parallèles.*Sous-agents.*Sources/);});
