'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{harness,source}=require('./frontend_test_dom.cjs');
function ephemeral(overrides={}){const h=harness(overrides);h.run(source.slice(source.indexOf('// Discussions éphémères :'),source.indexOf('// Fin des discussions éphémères partagées.')));h.run(source.slice(source.indexOf('let expressActive=null,'),source.indexOf("document.addEventListener('keydown',event=>{if(event.ctrlKey&&event.altKey&&event.key.toLowerCase()==='n')")));h.load('openQueuedParallelChat');return h;}
const tick=()=>new Promise(setImmediate);
function wire(h,action){return h.calls.filter(item=>item.action===action);}
test('ephemeral parent reference matches the visible URL and never leaks the last native chat from home',()=>{const h=ephemeral();assert.equal(h.ctx.ephemeralParentReference().id,'parent');h.ctx.location.search='';assert.equal(h.ctx.ephemeralParentReference(),null);h.ctx.location.search='?archive=archive';assert.equal(h.ctx.ephemeralParentReference().kind,'codex');h.ctx.location.search='?document=archive';assert.equal(h.ctx.ephemeralParentReference(),null);});
test('parallel create is deduplicated and sends text alone without client context or message injection',async()=>{const h=ephemeral({nativeSave(){throw Error('Parent mutation');},nativeState(){throw Error('Parent read');}});const [one,two]=await Promise.all([h.ctx.openParallelChat('parent'),h.ctx.openParallelChat('parent')]);assert.equal(one,two);assert.equal(wire(h,'workspace').length,1);assert.equal(wire(h,'create').length,1);one.context='MUST NOT SEND';one.messages.push({role:'assistant',content:'MUST NOT INJECT'});await h.ctx.sendEphemeralChat(one,'Exact question');assert.deepEqual(wire(h,'send'),[{action:'send',workspace:'opaque',id:one.id,text:'Exact question'}]);assert.equal(wire(h,'refresh').length,0);});
test('create result after navigation is closed without opening or selecting a side discussion',async()=>{let release;const h=ephemeral({fetchJSON:async(_path,options)=>{const v=JSON.parse(options.body);h.calls.push(v);if(v.action==='workspace')return {workspace:'w'};if(v.action==='create')return new Promise(resolve=>release=resolve);return {};}});const work=h.ctx.openParallelChat('parent');await tick();h.ctx.requestSerial++;h.ctx.nativeCurrent='other';release({id:'late',kind:'parallel'});assert.equal(await work,null);assert.equal(h.run('parallelChats.size'),0);assert.equal(h.document.getElementById('parallel-chats'),null);assert.equal(wire(h,'close').length,1);});
test('collapse during parallel creation invalidates its result',async()=>{let release;const h=ephemeral({fetchJSON:async(_p,o)=>{const v=JSON.parse(o.body);h.calls.push(v);return v.action==='workspace'?{workspace:'w'}:v.action==='create'?new Promise(r=>release=r):{};}}),pending=h.ctx.openParallelChat('parent');await tick();h.ctx.closeAllParallelChats();release({id:'late'});assert.equal(await pending,null);assert.equal(wire(h,'close').length,1);});
test('express refreshes the visible parent before each send, without transmitting parallel content from client',async()=>{const h=ephemeral();await h.ctx.openExpressBubble();const chat=h.run('expressActive');await h.ctx.sendEphemeralChat(chat,'One');h.ctx.location.search='?archive=archive';await h.ctx.sendEphemeralChat(chat,'Two');const refresh=wire(h,'refresh');assert.equal(refresh[0].parent.id,'parent');assert.equal(refresh[1].parent.id,'archive');assert.equal(wire(h,'send').every(item=>!('context' in item)&&!('messages' in item)),true);assert.equal(chat.messages.length,4);});
test('closing an express bubble erases draft/history and ignores a late model response',async()=>{let release;const h=ephemeral({fetchJSON:async(_p,o)=>{const v=JSON.parse(o.body);h.calls.push(v);if(v.action==='workspace')return {workspace:'w'};if(v.action==='create')return {id:'express'};if(v.action==='send')return new Promise(resolve=>release=resolve);return {};}});await h.ctx.openExpressBubble();const chat=h.run('expressActive'),pending=h.ctx.sendEphemeralChat(chat,'Private');await tick();h.ctx.closeExpressBubble();release({text:'Late private response'});await pending;assert.equal(chat.closed,true);assert.equal(chat.messages.length,0);assert.equal(h.run('expressActive'),null);assert.equal(h.document.getElementById('express-bubble'),null);assert.equal(wire(h,'close').length,1);});
test('double send during a request cannot duplicate a turn and failure restores the exact draft',async()=>{let reject;const h=ephemeral({fetchJSON:async(_p,o)=>{const v=JSON.parse(o.body);h.calls.push(v);if(v.action==='workspace')return {workspace:'w'};if(v.action==='create')return {id:'one'};if(v.action==='send')return new Promise((_r,j)=>reject=j);return {};}});const chat=await h.ctx.openParallelChat('parent'),work=h.ctx.sendEphemeralChat(chat,'Question intacte');assert.equal(await h.ctx.sendEphemeralChat(chat,'Duplicate'),false);reject(Error('503 unavailable'));await work;assert.equal(wire(h,'send').length,1);assert.equal(chat.draft,'Question intacte');assert.equal(chat.messages.length,0);assert.equal(chat.busy,false);assert.match(chat.error,/503/);});
test('retention is explicit, deduplicated, own-history only, and leaves the current main draft untouched',async()=>{let release;const h=ephemeral({corpusConfirm:()=>new Promise(resolve=>release=resolve)}),chat=await h.ctx.openParallelChat('parent');chat.messages.push({role:'user',content:'Own question'});const pending=h.ctx.retainEphemeralChat(chat);assert.equal(wire(h,'retain').length,0);assert.equal(await h.ctx.retainEphemeralChat(chat),null);release(true);const session=await pending;assert.equal(session.id,'saved');assert.equal(h.ctx.locals.length,1);assert.deepEqual(wire(h,'retain'),[{action:'retain',workspace:'opaque',id:chat.id}]);assert.equal(h.calls.some(v=>Array.isArray(v)&&v[0]==='open'),false);});
test('closing during retention confirmation prevents any persistence',async()=>{let release;const h=ephemeral({corpusConfirm:()=>new Promise(resolve=>release=resolve)}),chat=await h.ctx.openParallelChat('parent');chat.messages.push({role:'user',content:'Private'});const pending=h.ctx.retainEphemeralChat(chat);void h.ctx.closeEphemeralChat(chat);release(true);assert.equal(await pending,null);assert.equal(wire(h,'retain').length,0);});
test('queued-to-parallel transfer uses the returned chat and cannot overwrite another active temporary',async()=>{const h=ephemeral(),item={text:'My queue item'},state={id:'parent',queue:[item]};h.ctx.openParallelChat=async()=>null;h.run("parallelChats.set('other',{id:'other',draft:'Keep this',parentId:'other'});activeParallel='other'");await h.ctx.openQueuedParallelChat(state,item);assert.equal(h.run("parallelChats.get('other').draft"),'Keep this');assert.equal(state.queue.length,1);});
test('page close only sends workspace cleanup and does not persist private histories',async()=>{const h=ephemeral({localStorage:{setItem(){throw Error('Private persistence');}}});await h.ctx.openParallelChat('parent');await h.ctx.openExpressBubble();h.listeners.pagehide();assert.equal(h.run('parallelChats.size'),0);assert.equal(h.run('expressActive'),null);await assert.rejects(h.ctx.ensureEphemeralWorkspace(),/fermée/);});
test('a failed response preserves new typing and keeps the failed request separately recoverable',async()=>{let reject;const h=ephemeral({fetchJSON:async(_p,o)=>{const v=JSON.parse(o.body);if(v.action==='workspace')return {workspace:'w'};if(v.action==='create')return {id:'one'};if(v.action==='send')return new Promise((_r,j)=>reject=j);return {};}}),chat=await h.ctx.openParallelChat('parent'),pending=h.ctx.sendEphemeralChat(chat,'Original request');chat.draft='New draft typed while waiting';reject(Error('Model down'));await pending;assert.equal(chat.draft,'New draft typed while waiting');assert.equal(chat.failedDraft,'Original request');const form=h.ctx.ephemeralComposer(chat,()=>{},'Text');form.querySelector('.ephemeral-recover').click();assert.equal(chat.draft,'Original request\n\nNew draft typed while waiting');});
test('browser back-forward restoration starts an empty workspace and does not resurrect closed private DOM',async()=>{const h=ephemeral();const chat=await h.ctx.openParallelChat('parent');chat.messages.push({role:'assistant',content:'PRIVATE'});h.listeners.pagehide();h.listeners.pageshow({persisted:true});assert.equal(h.document.getElementById('parallel-chats'),null);assert.equal(chat.messages.length,0);await h.ctx.openParallelChat('parent');assert.equal(wire(h,'workspace').length,2);});
function fileHarness(overrides={}){const revoked=[],created=[],uploads=[];const h=ephemeral({URL:{createObjectURL:file=>{const url='blob:'+file.name;created.push(url);return url;},revokeObjectURL:url=>revoked.push(url)},FileReader:class{readAsDataURL(){this.result='data:text/plain;base64,UHJpdmF0ZQ==';this.onload();}},fetchJSON:async(_p,options)=>{const value=JSON.parse(options.body);h.calls.push(value);if(value.action==='workspace')return {workspace:'files-workspace'};if(value.action==='create')return {id:'files-chat'};if(value.action==='upload'){uploads.push(value);return {id:'attachment-'+uploads.length,name:value.name,mime:value.mime,kind:'document',preview:'Private extract',characters:15};}if(value.action==='send')return {text:'Understood'};return {};},...overrides});Object.assign(h,{revoked,created,uploads});return h;}
test('private file upload sends only to the temporary workspace and attachment-only messages use opaque ids',async()=>{const h=fileHarness(),chat=await h.ctx.openParallelChat('parent');await h.ctx.addEphemeralFiles(chat,[{name:'note.txt',type:'text/plain',size:12}],()=>{});assert.equal(chat.attachments.length,1);assert.equal(h.uploads[0].data,'UHJpdmF0ZQ==');assert.equal(h.uploads[0].workspace,'files-workspace');await h.ctx.sendEphemeralChat(chat,'');assert.deepEqual(wire(h,'send')[0],{action:'send',workspace:'files-workspace',id:'files-chat',text:'',attachments:['attachment-1']});assert.equal(chat.attachments.length,0);assert.equal(chat.messages[0].attachments[0].name,'note.txt');await h.ctx.closeEphemeralChat(chat);assert.deepEqual(h.revoked,['blob:note.txt']);});
test('files above the temporary limit are rejected before reading or creating any preview URL',async()=>{const h=fileHarness(),chat=await h.ctx.openParallelChat('parent');await h.ctx.addEphemeralFiles(chat,[{name:'huge.zip',size:13*1024*1024}],()=>{});assert.equal(h.uploads.length,0);assert.equal(h.created.length,0);assert.match(chat.error,/12 Mo/);});
test('removing an unsent private attachment deletes the server reference and revokes its local preview',async()=>{const h=fileHarness(),chat=await h.ctx.openParallelChat('parent');await h.ctx.addEphemeralFiles(chat,[{name:'remove.txt',type:'text/plain',size:10}],()=>{});const row=h.ctx.ephemeralAttachments(chat,chat.attachments,()=>{},true);await row.querySelector('[aria-label="Retirer remove.txt"]').click();assert.equal(chat.attachments.length,0);assert.deepEqual(wire(h,'remove-attachment')[0],{action:'remove-attachment',workspace:'files-workspace',id:'files-chat',attachment:'attachment-1'});assert.deepEqual(h.revoked,['blob:remove.txt']);});
test('file upload finishing after close cannot reattach to another temporary chat',async()=>{let release;const h=fileHarness({fetchJSON:async(_p,o)=>{const v=JSON.parse(o.body);h.calls.push(v);if(v.action==='workspace')return {workspace:'w'};if(v.action==='create')return {id:'c'};if(v.action==='upload')return new Promise(r=>release=r);return {};}}),chat=await h.ctx.openParallelChat('parent');const work=h.ctx.addEphemeralFiles(chat,[{name:'late.pdf',size:12,type:'application/pdf'}],()=>{});await tick();await h.ctx.closeEphemeralChat(chat);release({id:'late-file'});await work;assert.equal(chat.attachments.length,0);assert.equal(chat.closed,true);assert.deepEqual(h.revoked,['blob:late.pdf']);});
test('ephemeral composer installs shared drop and clipboard on its own form',async()=>{const hooks=[],h=fileHarness({installChatDropZone:(form,add)=>hooks.push(['drop',form,add]),installChatClipboard:(form,input,add)=>hooks.push(['paste',form,input,add])}),chat=await h.ctx.openParallelChat('parent');hooks.length=0;const form=h.ctx.ephemeralComposer(chat,()=>{},'Private input');assert.equal(hooks[0][1],form);assert.equal(hooks[1][2],form.querySelector('textarea'));await hooks[0][2]([{name:'drop.txt',size:4,type:'text/plain'}]);await hooks[1][3]([{name:'paste.txt',size:4,type:'text/plain'}]);assert.equal(chat.attachments.length,2);});
