'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {File}=require('node:buffer');
const {harness}=require('./frontend_test_dom.cjs');
function fixture(clipboard={}){
 const received=[];const h=harness({File,Event,innerWidth:600,innerHeight:500,navigator:{clipboard},MutationObserver:class{observe(){}disconnect(){}}});
 h.run('let chatClipboardMenuCleanup=null;');h.load('chatAttachmentError','installChatDropZone','installChatClipboard');
 const form=h.add('form','form'),input=h.add('input','textarea',form);input.value='Hello world';input.selectionStart=6;input.selectionEnd=11;input.select=()=>{input.selectionStart=0;input.selectionEnd=input.value.length;};input.setRangeText=(text,start,end)=>{input.value=input.value.slice(0,start)+text+input.value.slice(end);};input.dispatchEvent=event=>input['on'+event.type]?.(event);
 h.ctx.installChatDropZone(form,files=>received.push(files));h.ctx.installChatClipboard(form,input,files=>received.push(files));return {...h,form,input,received};
}
function gesture(extra={}){return {prevented:false,stopped:false,clientX:590,clientY:490,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...extra};}
function menu(h){h.input.oncontextmenu(gesture());return h.body.querySelector('.chat-clipboard-menu');}
test('file drop belongs to the receiving form and prevents browser navigation',async()=>{const h=fixture(),files=[{name:'document.pdf'}],event=gesture({dataTransfer:{types:['Files'],files}});h.form.ondragenter(event);assert(h.form.classList.contains('chat-drag-active'));h.form.ondrop(event);assert(event.prevented&&event.stopped);assert(!h.form.classList.contains('chat-drag-active'));assert.deepEqual(h.received,[files]);});
test('dragging text preserves normal editing and nested leaves keep file highlight until exit',()=>{const h=fixture(),text=gesture({dataTransfer:{types:['text/plain']}});h.form.ondrop(text);assert(!text.prevented);const e=gesture({dataTransfer:{types:['Files']}});h.form.ondragenter(e);h.form.ondragenter(e);h.form.ondragleave(e);assert(h.form.classList.contains('chat-drag-active'));h.form.ondragleave(e);assert(!h.form.classList.contains('chat-drag-active'));});
test('file clipboard paste uses attachments while ordinary text keeps native behavior',()=>{const h=fixture(),file={name:'screen.png'},image=gesture({clipboardData:{files:[file]}}),text=gesture({clipboardData:{files:[]}});h.input.onpaste(image);h.input.onpaste(text);assert(image.prevented);assert(!text.prevented);assert.deepEqual(h.received,[[file]]);});
test('right click does not read clipboard until Paste; one image representation becomes one file',async()=>{let reads=0;const h=fixture({read:async()=>{reads++;return [{types:['image/png','image/webp','text/html'],getType:async type=>new Blob(['PNG'],{type})}];}}),m=menu(h);assert.equal(reads,0);await m.children[0].click();assert.equal(reads,1);assert.equal(h.received.length,1);assert.equal(h.received[0].length,1);assert.equal(h.received[0][0].type,'image/png');assert.equal(h.body.querySelector('.chat-clipboard-menu'),null);});
test('right click paste inserts plain text at the saved selection and persists input',async()=>{const h=fixture({read:async()=>[{types:['text/plain'],getType:async()=>new Blob(['Corpus'])}]}),m=menu(h);let saved='';h.input.oninput=()=>saved=h.input.value;await m.children[0].click();assert.equal(saved,'Hello Corpus');});
test('clipboard refusal leaves draft and attachments intact with a usable fallback',async()=>{const h=fixture({read:async()=>{throw Error('Denied');}}),m=menu(h);await m.children[0].click();assert.equal(h.input.value,'Hello world');assert.equal(h.received.length,0);assert.match(h.form.textContent,/Ctrl\+V/);});
test('late clipboard text cannot overwrite an input detached by navigation',async()=>{let resolve;const h=fixture({read:()=>new Promise(r=>resolve=r)}),m=menu(h),work=m.children[0].click();h.input.remove();resolve([{types:['text/plain'],getType:async()=>new Blob(['Late'])}]);await work;assert.equal(h.input.value,'Hello world');});
test('opening another clipboard menu cleans up its predecessor and Escape restores focus',()=>{const h=fixture(),first=menu(h),second=menu(h);assert(!first.isConnected);assert(second.isConnected);second.onkeydown(gesture({key:'Escape'}));assert(!second.isConnected);assert.equal(h.focus,h.input);});
