'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
process.env.TZ='Europe/Paris';
const source=fs.readFileSync(__dirname+'/portal/app.js','utf8');
function harness(saved='false'){
 class Node{
  constructor(tag,text='',cls=''){this.tagName=tag.toUpperCase();this.textContent=text;this.className=cls;this.children=[];this.dataset={};this.attrs={};this.scrollTop=0;this.classList={add:name=>{if(!this.className.split(' ').includes(name))this.className+=' '+name;},remove:name=>{this.className=this.className.split(' ').filter(x=>x!==name).join(' ');},toggle:(name,state)=>state?this.classList.add(name):this.classList.remove(name),contains:name=>this.className.split(' ').includes(name)};}
  append(...nodes){this.children.push(...nodes);for(const n of nodes)n.parent=this;}
  replaceChildren(...nodes){this.children=[];this.append(...nodes);}
  setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k];}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}
  querySelectorAll(selector){return this.children.flatMap(n=>[...((selector.startsWith('.')?n.classList.contains(selector.slice(1)):n.tagName===selector.toUpperCase())?[n]:[]),...n.querySelectorAll(selector)]);}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 }
 const nodes=Object.fromEntries(['list','list-title','count','sidebar-activity-toggle','sidebar-toggle','search','archived'].map(id=>[id,new Node(id==='search'?'input':'div')]));nodes.search.value='';nodes.archived.checked=false;
 const results=new Node('section'),sidebar=new Node('aside'),body=new Node('body');results.append(nodes.list);sidebar.append(results);body.append(sidebar);const storage=new Map([['corpus.sidebar-activity.v1',saved]]),sessions=new Map(),groups=new Map();let ordinaryRenders=0,projectReads=0;
 const document={body,visibilityState:'hidden',querySelector:s=>s==='.results'?results:s==='body>.sidebar'?sidebar:null,querySelectorAll:()=>[]};
 const box={document,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},nativeSessions:sessions,nativeSubagentGroups:groups,Date,AbortSignal,URLSearchParams,location:{search:'?session=live'},kind:'Conversations',library:{root:'/Corpus',threads:[],documents:[]},locals:[],sidebarRenderSerial:0,searchIds:null,$:id=>nodes[id],el:(...args)=>new Node(...args),corpusProjectPrefs:()=>({name:'Corpus'}),conversationUpdatedAt:item=>{const value=item.time?.updated??item.updated_at??0;return typeof value==='number'?(value<1e12?value*1000:value):Date.parse(value)||0;},archiveState:item=>item.state||'active',corpusIcon:()=>new Node('svg'),sidebarConversationRow:(item,open)=>{const row=new Node('div','','sidebar-conversation');row.dataset.session=item.id;row.append(open);return row;},shortcutBindings:{sidebarActivity:'Ctrl+Alt+U'},setInterval(){},show:async item=>{box.opened=item;box.location.search='?session='+item.id;},renderOrganizedSidebar:()=>{ordinaryRenders++;nodes.list.append(new Node('section','Épinglés / Projets / Récents','organized-group'));},showRegisteredProjects:()=>projectReads++};
 vm.createContext(box);
 vm.runInContext(source.slice(source.indexOf('// Vue Activité :'),source.indexOf('// Fin de la vue Activité.'))+'\n'+source.slice(source.indexOf('function render(){'),source.indexOf('async function show(item)'))+'\nthis.api={recordSidebarActivityNative,pollSidebarActivity,nativeCache:sidebarActivityNative,sidebarActivityPriority,sidebarActivityUpdatedAt,sidebarActivityProject,sidebarActivityGroups,toggleSidebarActivity,refreshSidebarActivity,renderSidebarActivity,updateSidebarActivityButton,active:()=>sidebarActivityEnabled};',box);
 return {box,api:box.api,nodes,sessions,groups,storage,results,sidebar,Node,get ordinaryRenders(){return ordinaryRenders;},get projectReads(){return projectReads;}};
}
const date=value=>new Date(value).getTime();
test('Activity groups real active/approval work first and remaining chats by local calendar day across DST',()=>{
 const h=harness(),now=date('2026-03-30T12:00:00+02:00'),rows=[{id:'today',time:{updated:now-1000}},{id:'yesterday',time:{updated:date('2026-03-29T00:30:00+01:00')}},{id:'saturday',time:{updated:date('2026-03-28T15:00:00+01:00')}},{id:'active',time:{updated:date('2026-03-01T12:00:00Z')}},{id:'approval',updated_at:1700000000},{id:'unknown'}];h.sessions.set('active',{busy:true});h.groups.set('approval',{permissions:[{id:'ask'}]});const groups=h.api.sidebarActivityGroups(rows,now);assert.equal(groups[0].title,'Priorité');assert.deepEqual(Array.from(groups[0].rows,r=>r.id).sort(),['active','approval']);assert.deepEqual(Array.from(groups.slice(1),g=>g.title),['Aujourd’hui','Hier','samedi','Date inconnue']);
});
test('pinning does not invent active work; imported seconds and live messages yield honest activity dates',()=>{
 const h=harness(),item={id:'live',is_pinned:true,updated_at:1700000000};assert.equal(h.api.sidebarActivityPriority(item),false);assert.equal(h.api.sidebarActivityUpdatedAt(item),1700000000000);h.sessions.set('live',{messages:[{info:{time:{created:1800000000000,completed:1800000000500}}}]});assert.equal(h.api.sidebarActivityUpdatedAt(item),1800000000500);assert.equal(h.api.sidebarActivityPriority(item),false);
});
test('bell toggles Activity in the existing sidebar and restores normal organisation/scroll without changing chat',()=>{
 const h=harness();h.box.locals=[{id:'live',title:'Local chat',directory:'/Corpus',time:{updated:Date.now()}}];h.box.render();h.results.scrollTop=240;h.api.toggleSidebarActivity();assert.equal(h.api.active(),true);assert.equal(h.nodes['sidebar-activity-toggle'].getAttribute('aria-pressed'),'true');assert.match(h.nodes['sidebar-activity-toggle'].title,/Désactiver.*Ctrl\+Alt\+U/);assert.equal(h.nodes.list.classList.contains('sidebar-activity'),true);assert.equal(h.nodes.list.querySelectorAll('.sidebar-activity-project').length,1);assert.equal(h.box.location.search,'?session=live');assert.equal(h.ordinaryRenders,1);h.results.scrollTop=80;h.api.toggleSidebarActivity();assert.equal(h.api.active(),false);assert.equal(h.results.scrollTop,240);assert.equal(h.ordinaryRenders,2);assert.equal(h.nodes.list.classList.contains('sidebar-activity'),false);assert.equal(h.storage.get('corpus.sidebar-activity.v1'),'false');assert.equal(h.box.location.search,'?session=live');h.api.toggleSidebarActivity();assert.equal(h.results.scrollTop,80);
});
test('Activity survives reload, filters archived/trash/child rows, and opens the original conversation',async()=>{
 const h=harness('true');h.box.locals=[{id:'live',title:'Local',directory:'/Corpus',time:{updated:Date.now()}},{id:'child',parentID:'live',title:'Hidden child'},{id:'trash',state:'trash',title:'Trash'},{id:'archived',state:'archived',title:'Archived'}];h.box.library.threads=[{id:'imported',title:'Imported',cwd:'/other/project',updated_at:1700000000}];h.box.render();const rows=h.nodes.list.querySelectorAll('.sidebar-conversation');assert.deepEqual(rows.map(r=>r.dataset.session),['live','imported']);const imported=rows[1];await imported.querySelector('.entry').onclick();assert.equal(h.box.opened.id,'imported');assert.equal(h.api.active(),true);assert.equal(h.ordinaryRenders,0);assert.equal(h.projectReads,0);assert.equal(imported.classList.contains('selected'),true);assert.equal(h.api.sidebarActivityProject(h.box.library.threads[0]),'project');
});
test('unchanged activity polling preserves DOM; a real completion moves the item from Priority without changing scroll',()=>{
 const h=harness('true');h.box.locals=[{id:'live',title:'Local',time:{updated:Date.now()}}];h.sessions.set('live',{busy:true});h.box.render();h.results.scrollTop=90;const section=h.nodes.list.children[0];assert.equal(section.dataset.activityGroup,'priority');h.api.refreshSidebarActivity();assert.equal(h.nodes.list.children[0],section);h.sessions.get('live').busy=false;h.api.refreshSidebarActivity();assert.notEqual(h.nodes.list.children[0],section);assert.match(h.nodes.list.children[0].dataset.activityGroup,/^day:/);assert.equal(h.results.scrollTop,90);
});
test('long activity lists load more in place and preserve the current filter',()=>{
 const h=harness('true');h.box.locals=Array.from({length:90},(_,i)=>({id:'x'+i,title:'Selected '+i,time:{updated:Date.now()-i}}));h.nodes.search.value='selected';h.box.render();assert.equal(h.nodes.list.querySelectorAll('.sidebar-conversation').length,30);h.nodes.list.querySelector('.sidebar-show-more').onclick();assert.equal(h.nodes.list.querySelectorAll('.sidebar-conversation').length,60);assert.equal(h.nodes.search.value,'selected');h.api.refreshSidebarActivity();assert.equal(h.nodes.list.querySelectorAll('.sidebar-conversation').length,60);
});

test('global native status and child approvals identify active parents never opened in this page',()=>{
 const h=harness();h.api.recordSidebarActivityNative({unopened:{type:'busy'},child:{type:'retry'}},[{id:'ask',sessionID:'child-permission'}],[{id:'child',parentID:'parent'},{id:'child-permission',parentID:'other-parent'}]);for(const id of ['unopened','parent','other-parent'])assert.equal(h.api.sidebarActivityPriority({id}),true);assert.equal(h.sessions.size,0);h.api.recordSidebarActivityNative({},[],[]);assert.equal(h.api.sidebarActivityPriority({id:'unopened'}),false);assert.equal(h.api.sidebarActivityPriority({id:'parent'}),false);
});
test('global Activity reads are bounded, non-overlapping, retain roots and never open a conversation',async()=>{
 const h=harness('true'),requests=[];h.box.document.visibilityState='visible';let release;h.box.fetchJSON=async path=>{requests.push(path);if(path==='/session/status'){await new Promise(resolve=>release=resolve);return {newRoot:{type:'busy'}};}if(path==='/permission')return [];return [{id:'newRoot',title:'Previously unopened',time:{updated:Date.now()}},{id:'worker',parentID:'newRoot'}];};const first=h.api.pollSidebarActivity(),second=h.api.pollSidebarActivity();assert.equal(first,second);assert.equal(requests.length,3);release();await first;assert.equal(h.api.sidebarActivityPriority({id:'newRoot'}),true);assert.deepEqual(Array.from(h.box.locals,s=>s.id),['newRoot']);assert.equal(h.box.opened,undefined);assert.equal(h.box.location.search,'?session=live');await h.api.pollSidebarActivity();assert.equal(requests.length,3,'Fresh global caches do not refetch or fan out per conversation');
});
test('parent mapping cycles are bounded and failed global reads retain last active evidence with an error',async()=>{
 const h=harness('true');h.api.recordSidebarActivityNative({old:{type:'busy'},a:{type:'busy'}},[],[{id:'a',parentID:'b'},{id:'b',parentID:'a'}]);assert.equal(h.api.sidebarActivityPriority({id:'a'}),false);assert.equal(h.api.sidebarActivityPriority({id:'old'}),true);h.api.nativeCache.statusAt=0;h.api.nativeCache.permissionAt=0;h.box.document.visibilityState='visible';h.box.fetchJSON=async()=>{throw Error('503 unavailable');};await h.api.pollSidebarActivity();assert.match(h.api.nativeCache.error,/503 unavailable/);assert.equal(h.api.sidebarActivityPriority({id:'old'}),true);
});
