import test from "node:test";
import assert from "node:assert/strict";

import {
  collectYouTubeLocalEvidence
} from "../lib/youtube-resolution-evidence.mjs";

test(
  "les champs explicites Topic produisent une preuve forte",
  () => {
    const result =
      collectYouTubeLocalEvidence({
        title: "Disco Science",
        channelTitle: "Mirwais - Topic",
        description: [
          "Provided to YouTube",
          "",
          "Disco Science · Mirwais",
          "",
          "Main Artist: Mirwais",
          "Auto-generated by YouTube."
        ].join("\n")
      });

    assert.equal(
      result.topicChannel,
      "Mirwais"
    );

    assert.ok(
      result.observations.some(
        (item) =>
          item.value === "Mirwais" &&
          item.strength >= 0.94
      )
    );
  }
);
