import test from "node:test";
import assert from "node:assert/strict";
import { assessExpiringContestableSuspension, effectiveObserverRegistry, CctExpiringContestableSuspensionRuntime } from "./runtime.mjs";
import { audit, axes, completeExercise, initialCheckpointMemory, selectorRegistry, suspensionEndorsements, suspensionFixture, transitionFixture, validAmendment, validEndorsements, validValidation } from "./fixtures.mjs";
function setup() { const validation = validValidation(); const memory = initialCheckpointMemory(validation); const transition = transitionFixture(memory, true); const selectors = selectorRegistry(); const admission = validEndorsements(transition); const suspension = suspensionFixture(transition, validation); return { validation, memory, transition, selectors, admission, suspension }; }
function assess(s, suspension = s.suspension, endorsements = suspensionEndorsements(suspension, s.selectors), history = []) { return assessExpiringContestableSuspension(axes, audit, completeExercise(), validAmendment(), s.validation, s.memory, s.transition, s.selectors, s.admission, suspension, endorsements, history); }
test("suspends temporarily without mutating the admitted registry", () => { const s = setup(); const result = assess(s); assert.equal(result.status, "expiring_contestable_suspension_candidate"); assert.equal(result.registryMutated, false); assert.equal(result.automaticReturn, true); assert.equal(effectiveObserverRegistry(s.transition.newRegistry, s.suspension, s.suspension.openedAtTick).length, s.transition.newRegistry.length - 1); });
test("automatically restores quorum eligibility at expiry", () => { const s = setup(); assert.deepEqual(effectiveObserverRegistry(s.transition.newRegistry, s.suspension, s.suspension.endsAtTick), s.transition.newRegistry); });
test("refuses overlong suspension and renewal from the same incident", () => { const s = setup(); const overlong = suspensionFixture(s.transition, s.validation, { endsAtTick: s.suspension.openedAtTick + 13 }); assert.equal(assess(s, overlong).status, "not_established"); assert.deepEqual(assess(s, s.suspension, suspensionEndorsements(s.suspension, s.selectors), [s.suspension.incidentDigest]).failures, ["bounded_suspension_invalid"]); });
test("refuses unilateral or unsigned suspension", () => { const s = setup(); assert.deepEqual(assess(s, s.suspension, suspensionEndorsements(s.suspension, s.selectors).slice(0, 1)).failures, ["suspension_selector_quorum_missing"]); });
test("runtime blocks an unproved suspension", () => { const runtime = new CctExpiringContestableSuspensionRuntime(); runtime.state.phase = "staged_restoration_receipt_pending"; runtime.state.debts = axes.map((axis) => ({ axis, status: "open" })); assert.throws(() => runtime.decide({ view: { cct: { tick: 30 } }, allowedActions: ["suspend"] }), { message: /CCT_BOUNDED_OBSERVER_SUSPENSION_UNESTABLISHED/ }); });
