export type Access = "libre" | "orientation" | "inscription" | "carte";

export type FoodPlace = {
  id: string;
  name: string;
  arrondissement: string;
  service: string;
  audience: string;
  access: Access;
  days: number[];
  schedule: string;
  address: string;
  metro?: string;
  phone?: string;
  email?: string;
  note?: string;
  verify?: boolean;
  activeFrom?: string;
  activeUntil?: string;
  reviewAfter?: string;
  closures?: Array<[string, string]>;
  sourcePage: number;
  sourceUrl?: string;
  sourceLabel?: string;
};

const SOLIDARY_RESTAURANTS_SOURCE =
  "https://cdn.paris.fr/paris/2026/06/04/diner-dans-les-restaurants-solidaires-depliant-v5-03-06-2026-web-PryP.pdf";

const solidaryRestaurantCommon = {
  audience: "Personnes en grande précarité, seules ou familles, avec carte mensuelle",
  access: "carte" as const,
  reviewAfter: "2026-09-30",
  email: "casvp-did-restaurants-solidaires@paris.fr",
  note: "Carte nominative mensuelle délivrée par un service social, une permanence sociale, un ESI, une association ou une maraude.",
  sourcePage: 4,
  sourceUrl: `${SOLIDARY_RESTAURANTS_SOURCE}#page=4`,
  sourceLabel: "Dépliant officiel juin 2026",
};

export const places: FoodPlace[] = [
  {
    id: "aspp-hotel-de-ville",
    name: "ASPP Hôtel-de-Ville",
    arrondissement: "Centre",
    service: "Repas chauds assis",
    audience: "Tout public",
    access: "libre",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours, 18h-20h",
    address: "9, place de l’Hôtel de Ville",
    metro: "Hôtel de Ville",
    activeFrom: "2026-07-13",
    activeUntil: "2026-08-30",
    sourcePage: 42,
  },
  {
    id: "saint-merry",
    name: "Paroisse Saint-Merry",
    arrondissement: "Centre",
    service: "Petits déjeuners ; déjeuner le dimanche",
    audience: "Tout public",
    access: "libre",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Petit déjeuner 8h15-9h15 ; dimanche 13h-14h",
    address: "76, rue de la Verrerie",
    metro: "Hôtel de Ville",
    phone: "01 42 71 93 93",
    sourcePage: 43,
  },
  {
    id: "cafe-ozanam",
    name: "Café Ozanam - Saint-Nicolas-des-Champs",
    arrondissement: "Centre",
    service: "Petits déjeuners",
    audience: "Tout public",
    access: "libre",
    days: [0, 2, 4],
    schedule: "Mardi et jeudi 8h15-9h ; dimanche 9h-10h",
    address: "254, rue Saint-Martin",
    metro: "Réaumur-Sébastopol",
    phone: "01 42 72 92 54",
    note: "Appeler le secrétariat en semaine, 9h30-12h30 ou 14h-18h.",
    sourcePage: 42,
  },
  {
    id: "restaurant-santeuil",
    name: "Restaurant social Santeuil - Aurore",
    arrondissement: "5e",
    service: "Repas chauds et paniers repas sous conditions",
    audience: "Tout public avec carte d’accès",
    access: "carte",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours, 11h30-14h10 et 17h30-19h40",
    address: "8, rue de Santeuil",
    metro: "Censier-Daubenton",
    sourcePage: 44,
  },
  {
    id: "saint-germain-des-pres",
    name: "Église Saint-Germain-des-Prés - Ordre de Malte",
    arrondissement: "6e",
    service: "Petits déjeuners",
    audience: "Tout public",
    access: "libre",
    days: [0],
    schedule: "Dimanche, 8h30-10h30",
    address: "3, place Saint-Germain-des-Prés",
    metro: "Saint-Germain-des-Prés ou Mabillon",
    email: "petitdejeuner@eglise-sgp.org",
    verify: true,
    sourcePage: 44,
  },
  {
    id: "saint-augustin",
    name: "Accueil Solidarité Saint-Augustin",
    arrondissement: "8e",
    service: "Colis alimentaires",
    audience: "Personnes orientées par les services sociaux des 8e, 9e ou 17e",
    access: "orientation",
    days: [2],
    schedule: "Mardi, 14h30-17h30",
    address: "Adresse communiquée lors de l’orientation",
    phone: "01 42 93 20 52",
    sourcePage: 45,
  },
  {
    id: "epalsl",
    name: "Entraide et Partage avec les Sans-Logis",
    arrondissement: "10e",
    service: "Petits déjeuners et repas",
    audience: "Tout public adulte",
    access: "libre",
    days: [0, 2, 3, 4, 5, 6],
    schedule: "Mar.-ven. 9h30-10h30 et 17h-18h ; sam. 12h-13h ; dim. 10h-11h",
    address: "22, rue Sainte-Marthe",
    metro: "Belleville ou Colonel-Fabien",
    phone: "09 54 17 62 30",
    sourcePage: 46,
  },
  {
    id: "missionnaires-charite",
    name: "Sœurs Missionnaires de la Charité",
    arrondissement: "11e",
    service: "Repas chauds complets sur place",
    audience: "Tout public majeur",
    access: "libre",
    days: [0, 1, 2, 3, 6],
    schedule: "Lundi-mercredi, samedi et dimanche, 8h45-11h",
    address: "60, rue de la Folie-Méricourt",
    metro: "Oberkampf ou Parmentier",
    phone: "01 43 55 79 01",
    sourcePage: 47,
  },
  {
    id: "linkee-13",
    name: "Linkee - ESS’pace",
    arrondissement: "13e",
    service: "Colis alimentaires et produits d’hygiène",
    audience: "Étudiants avec justificatif",
    access: "inscription",
    days: [1],
    schedule: "Lundi, 19h30-21h",
    address: "15, rue Jean-Antoine-de-Baïf",
    metro: "Bibliothèque François-Mitterrand",
    phone: "09 63 51 39 78",
    note: "Inscription sur linkee.co.",
    sourcePage: 48,
  },
  {
    id: "cop1ne",
    name: "La Cop1ne - Restaurant solidaire",
    arrondissement: "14e",
    service: "Repas à tarif solidaire",
    audience: "Étudiants",
    access: "libre",
    days: [2, 3, 4, 5, 6],
    schedule: "Mardi-samedi, 12h-13h30 et 19h30-21h30",
    address: "1, place Alice-Guy",
    metro: "T3b Didot - Porte de Vanves",
    phone: "07 60 16 80 14",
    email: "contact@lacop1ne.fr",
    note: "3 € pour deux éléments ; 5 € pour entrée-plat-dessert.",
    activeFrom: "2026-08-16",
    sourcePage: 50,
  },
  {
    id: "cantine-arbustes",
    name: "La Cantine des Arbustes",
    arrondissement: "14e",
    service: "Déjeuners à tarif préférentiel ou gratuits sur justificatif",
    audience: "Tout public",
    access: "libre",
    days: [1, 2, 3, 4, 5],
    schedule: "Lundi-vendredi, 11h30-14h30",
    address: "5, rue des Arbustes",
    metro: "Porte de Vanves",
    phone: "06 50 94 54 09",
    email: "arbustes@refugee-food.org",
    verify: true,
    note: "Lieu très fréquenté : contacter avant de venir.",
    sourcePage: 50,
  },
  {
    id: "restaurant-atlas",
    name: "Restaurant Atlas - Aurore",
    arrondissement: "15e",
    service: "Repas chauds sur place et à emporter",
    audience: "Tout public orienté par un partenaire social",
    access: "orientation",
    days: [1, 2, 3, 4, 5],
    schedule: "Lundi-vendredi, 18h-19h",
    address: "20, rue du Clos-Feuquières",
    metro: "Convention",
    sourcePage: 51,
  },
  {
    id: "eglise-reformee",
    name: "Entraide de l’Église réformée",
    arrondissement: "16e",
    service: "Aide alimentaire",
    audience: "Tout public orienté par un service social du 16e",
    access: "orientation",
    days: [4],
    schedule: "Jeudi, 12h30-16h",
    address: "19, rue Cortambert",
    metro: "Rue de la Pompe",
    phone: "01 45 04 26 16",
    email: "entraideannonciation@gmail.com",
    sourcePage: 52,
  },
  {
    id: "sawa-ramey",
    name: "Foodtruck SAWA - Passage Ramey",
    arrondissement: "18e",
    service: "Aide alimentaire mobile",
    audience: "Tout public",
    access: "libre",
    days: [1],
    schedule: "Lundi, 9h-11h30",
    address: "Passage Ramey",
    email: "epicerie@sawa-asso.org",
    sourcePage: 53,
  },
  {
    id: "sawa-agutte",
    name: "Foodtruck SAWA - ESI Georgette-Agutte",
    arrondissement: "18e",
    service: "Aide alimentaire mobile",
    audience: "Tout public",
    access: "libre",
    days: [3, 5],
    schedule: "Mercredi et vendredi, 9h-14h",
    address: "13, rue Georgette-Agutte",
    email: "epicerie@sawa-asso.org",
    sourcePage: 53,
  },
  {
    id: "gamelle-jaures",
    name: "La Gamelle de Jaurès",
    arrondissement: "18e",
    service: "Distribution de repas",
    audience: "Tout public",
    access: "libre",
    days: [1],
    schedule: "Lundi, 20h-20h30",
    address: "29, avenue de la Porte-d’Aubervilliers",
    metro: "T3b Porte d’Aubervilliers",
    email: "lagamelledejaures@gmail.com",
    verify: true,
    sourcePage: 53,
  },
  {
    id: "soupe-de-nuit",
    name: "Soupe de Nuit - Armée du Salut",
    arrondissement: "18e",
    service: "Repas chauds en salle",
    audience: "Tout public avec carte d’une association partenaire",
    access: "carte",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours, 18h-20h ; femmes prioritaires 18h-18h15",
    address: "108, rue des Poissonniers",
    metro: "Marcadet-Poissonniers",
    sourcePage: 53,
  },
  {
    id: "table-ouverte",
    name: "La Table Ouverte",
    arrondissement: "18e",
    service: "Repas chauds",
    audience: "Tout public",
    access: "libre",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours à 12h",
    address: "4, rue des Poissonniers",
    metro: "Barbès-Rochechouart",
    phone: "06 29 94 61 33",
    email: "latableouverte@orange.fr",
    verify: true,
    sourcePage: 53,
  },
  {
    id: "secours-populaire-18",
    name: "Libre-service solidaire - Secours populaire",
    arrondissement: "18e",
    service: "Libre-service alimentaire",
    audience: "Personnes orientées par une antenne du Secours populaire",
    access: "orientation",
    days: [2, 3, 4, 5, 6],
    schedule: "Mar.-ven. 13h45-17h30 ; mer. dès 10h30 ; sam. 10h30-12h30 et 14h-17h30",
    address: "Adresse communiquée après orientation",
    closures: [
      ["2026-08-10", "2026-08-16"],
      ["2026-08-24", "2026-08-30"],
    ],
    sourcePage: 54,
  },
  {
    id: "ptits-dej-solidaires",
    name: "P’tits Déj’ Solidaires",
    arrondissement: "18e",
    service: "Petits déjeuners",
    audience: "Tout public",
    access: "libre",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours, 8h30-9h30",
    address: "Jardin d’Éole, entrée face au 21 rue du Département",
    metro: "Stalingrad",
    email: "ptitsdej@gmail.com",
    sourcePage: 54,
  },
  {
    id: "porte-villette",
    name: "Distribution alimentaire Porte de la Villette",
    arrondissement: "19e",
    service: "Repas - Restos du Cœur, La Chorba et L’Un est L’Autre",
    audience: "Tout public",
    access: "libre",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Lun.-ven. 11h-13h et 18h-20h ; week-end 12h-14h et 18h-20h",
    address: "7-15, avenue de la Porte-de-la-Villette",
    metro: "Porte de la Villette",
    sourcePage: 55,
  },
  {
    id: "chorba-pour-tous",
    name: "Une Chorba Pour Tous",
    arrondissement: "19e",
    service: "Repas chauds",
    audience: "Tout public",
    access: "libre",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi à partir de 16h",
    address: "135, boulevard de la Villette, sortie du métro",
    metro: "Jaurès",
    sourcePage: 56,
  },
  {
    id: "anrs-jeunes",
    name: "Permanence accueil jeunes - ANRS",
    arrondissement: "20e",
    service: "Petits déjeuners",
    audience: "Femmes et hommes de 12 à 25 ans en situation d’errance",
    access: "libre",
    days: [1, 2, 3, 4, 5],
    schedule: "Lundi-vendredi, 9h30-11h",
    address: "24, rue Ramponeau",
    metro: "Belleville",
    sourcePage: 57,
  },
  {
    id: "saint-blaise",
    name: "Restaurant Saint-Blaise - Armée du Salut",
    arrondissement: "20e",
    service: "Repas du soir",
    audience: "Tout public",
    access: "libre",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "2-4, rue du Clos",
    metro: "Maraîchers",
    activeFrom: "2026-07-13",
    activeUntil: "2026-08-30",
    sourcePage: 58,
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-boutebrie",
    name: "Restaurant solidaire Boutebrie",
    arrondissement: "5e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "15, rue de la Parcheminerie",
    metro: "Maubert, Odéon ou Saint-Michel Notre-Dame",
    phone: "01 46 34 72 14",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-europe",
    name: "Restaurant solidaire Europe",
    arrondissement: "8e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h45-19h30",
    address: "11, rue de Maleville",
    metro: "Miromesnil",
    phone: "01 45 63 52 57",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-vellefaux",
    name: "Restaurant solidaire Vellefaux",
    arrondissement: "10e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "66, avenue Claude-Vellefaux",
    metro: "Colonel-Fabien",
    phone: "01 40 40 78 04",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-chanzy",
    name: "Restaurant solidaire Chanzy",
    arrondissement: "11e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "6, rue de Chanzy",
    metro: "Charonne ou Faidherbe-Chaligny",
    phone: "01 43 71 28 08",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-saint-eloi",
    name: "Restaurant solidaire Saint-Éloi",
    arrondissement: "12e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "10, rue Eugénie-Éboué",
    metro: "Montgallet ou Reuilly-Diderot",
    phone: "01 43 46 97 66",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-baudricourt",
    name: "Restaurant solidaire Baudricourt",
    arrondissement: "13e",
    service: "Déjeuner et dîner assis",
    days: [0, 1, 2, 3, 4, 5, 6],
    schedule: "Tous les jours, 11h-13h et 18h-19h30",
    address: "15, rue de Baudricourt",
    metro: "Olympiades",
    phone: "01 45 83 32 60",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-artistes",
    name: "Restaurant solidaire Artistes",
    arrondissement: "14e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "55-57, rue du Montparnasse",
    metro: "Montparnasse-Bienvenüe ou Vavin",
    phone: "01 43 21 65 38",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-joseph-de-maistre",
    name: "Restaurant solidaire Joseph de Maistre",
    arrondissement: "18e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "86-88, rue Joseph-de-Maistre",
    metro: "Guy-Môquet",
    phone: "01 46 27 27 61",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-palikao",
    name: "Restaurant solidaire Palikao",
    arrondissement: "20e",
    service: "Déjeuner et dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Déjeuner lun.-ven. 12h-13h30 ; dîner lun.-sam. 17h15-19h15",
    address: "11-15, rue de Pali-Kao",
    metro: "Couronnes ou Belleville",
    phone: "01 58 71 13 13",
  },
  {
    ...solidaryRestaurantCommon,
    id: "solidaire-reservoir",
    name: "Restaurant solidaire Réservoir",
    arrondissement: "20e",
    service: "Dîner assis",
    days: [1, 2, 3, 4, 5, 6],
    schedule: "Lundi-samedi, 17h15-19h15",
    address: "2-4, rue de la Justice",
    metro: "Saint-Fargeau",
    phone: "01 40 30 06 94",
  },
];

export const accessLabels: Record<Access, string> = {
  libre: "Accès libre",
  orientation: "Sur orientation",
  inscription: "Sur inscription",
  carte: "Carte d’accès requise",
};
