// Audit de diagnostic : ne modifie pas les fichiers applicatifs ni le coffre réel.
// Firefox/Geckodriver requis ; voir README.md dans ce dossier.
import http from 'node:http';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {pathToFileURL,fileURLToPath} from 'node:url';
const project=fileURLToPath(new URL('../../',import.meta.url));
const dir=await mkdtemp('/tmp/mubi-audit-');
const findings=[]; let sid,app; const failPages=new Set();
const movies=Array.from({length:64},(_,i)=>({id:i+1,title:`${['Alpha','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel'][i%8]} ${i+1}`,original_title:`Original ${i+1}`,genre_ids:[[53,80],[18,99],[35,10749],[27,53],[14,16],[18,53],[99],[35]][i%8],vote_average:7+i%10/10,vote_count:100+i*30,release_date:`${1990+i%35}-01-01`,original_language:['fr','en','ja','fa'][i%4],popularity:100-i,overview:`Synopsis du film ${i+1}.`}));
for(const m of movies)m.original_title=`Oeuvre${m.id}`;
const source=http.createServer((req,res)=>{
 const u=new URL(req.url,'http://fixture'); const json=(x,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(x));};
 if(u.pathname==='/configuration')return json({images:{}});
 if(u.pathname==='/watch/providers/movie')return json({results:[{provider_id:11,provider_name:'MUBI'}]});
 if(u.pathname==='/discover/movie'){
  const min=Number(u.searchParams.get('primary_release_date.gte')?.slice(0,4)||1874),max=Number(u.searchParams.get('primary_release_date.lte')?.slice(0,4)||2026);
  let a=movies.filter(m=>Number(m.release_date.slice(0,4))>=min&&Number(m.release_date.slice(0,4))<=max&&m.vote_average>=Number(u.searchParams.get('vote_average.gte')||0)&&m.vote_count>=Number(u.searchParams.get('vote_count.gte')||0));
  const g=(u.searchParams.get('with_genres')||'').split(/[|,]/).map(Number).filter(Boolean);if(g.length)a=a.filter(m=>m.genre_ids.some(x=>g.includes(x)));
  const page=Number(u.searchParams.get('page')||1);if(failPages.has(page))return json({error:'fixture page error'},503);return json({total_pages:Math.max(1,Math.ceil(a.length/20)),total_results:a.length,results:a.slice((page-1)*20,page*20)});
 }
 if(/^\/movie\/\d+$/.test(u.pathname)){
  const id=Number(u.pathname.split('/').pop());const m=movies.find(m=>m.id===id)||{...movies[0],id,title:`Imported ${id}`};
  return json({...m,runtime:75+id%6*10,genres:m.genre_ids.map(id=>({id})),credits:{crew:[{job:'Director',name:`Director ${id%5}`}],cast:[{name:'Cast',character:'Role'}]},keywords:{keywords:[{name:'friendship'},{name:id%2?'single location':'nonlinear timeline'}]},external_ids:{imdb_id:`tt${String(id).padStart(7,'0')}`},'watch/providers':{results:{FR:{flatrate:id===64?[]:[{provider_id:11}]}}}});
 }
 json({},404);
});
source.listen(0,'127.0.0.1');await once(source,'listening');
const probe=http.createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));
const base=`http://127.0.0.1:${port}`;
const env={...process.env,PORT:String(port),TMDB_ROOT:`http://127.0.0.1:${source.address().port}`,TMDB_READ_TOKEN:'audit-fake-token',SOURCE_CONFIG_PATH:`${dir}/sources.json`,CACHE_PATH:`${dir}/cache.json`};
for(const key of ['GUARDIAN_API_KEY','NYT_API_KEY','OMDB_API_KEY','SCOUT_LLM_URL','SCOUT_LLM_MODEL'])delete env[key];
app=spawn(process.execPath,['server.mjs'],{cwd:project,env,stdio:['ignore','pipe','pipe']});await once(app.stdout,'data');
async function wd(path,body,method=body===undefined?'GET':'POST'){
 const r=await fetch(`${process.env.SCOUT_WEBDRIVER_URL || 'http://127.0.0.1:4451'}${path}`,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(j.value?.error)throw Error(j.value.error+': '+j.value.message);return j.value;
}
const js=(script,...args)=>wd(`/session/${sid}/execute/sync`,{script,args});
const click=(s)=>js('const e=document.querySelector(arguments[0]);if(!e)throw Error("Missing "+arguments[0]);e.click();',s);
const value=(s,v)=>js('const e=document.querySelector(arguments[0]);e.value=arguments[1];e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));',s,v);
const checked=(s,b)=>js('const e=document.querySelector(arguments[0]);if(e.checked!==arguments[1])e.click();',s,b);
async function wait(expr,ms=7000){let end=Date.now()+ms;while(Date.now()<end){if(await js(`return Boolean(${expr})`))return;await delay(50);}throw Error('Timeout '+expr);}
const text=(s)=>js('return document.querySelector(arguments[0])?.textContent',s);
const titles=()=>js('return [...document.querySelectorAll("#movies h3")].map(e=>e.textContent)');
const prefs=()=>js('return JSON.parse(localStorage.getItem("mubi-film-scout.preferences.v1")||"{}")');
const pass=(name,ok,observed)=>{findings.push({name,status:ok?'PASS':'FAIL',observed});console.log(JSON.stringify(findings.at(-1)));};
async function test(name,fn){try{await fn();}catch(e){findings.push({name,status:'ERROR',observed:e.message});console.log(JSON.stringify(findings.at(-1)));}}
async function reset(){await wd(`/session/${sid}/url`,{url:base});await js('localStorage.clear();sessionStorage.clear()');await wd(`/session/${sid}/refresh`,{});await wait('document.querySelectorAll("#profile-like input").length===18');await js('window.auditErrors=[];addEventListener("error",e=>auditErrors.push(e.message));addEventListener("unhandledrejection",e=>auditErrors.push(String(e.reason)));window.auditAlerts=[];window.alert=m=>auditAlerts.push(m);window.confirm=()=>true;');}
async function search(){await js('document.querySelector("#search-form").hidden=false;document.querySelector("#search-form").requestSubmit()');await wait('document.querySelector("#submit-search").disabled===false && document.querySelector("#programme-tools").hidden===false');await delay(200);}
async function panel(id){await js('document.querySelector("#discovery-workshop").open=true');await click(`[data-panel="${id}"]`);}
const post=async(path,body)=>{const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body)});return {status:r.status,body:await r.text()};};
try{
 const created=await wd('/session',{capabilities:{alwaysMatch:{browserName:'firefox','moz:firefoxOptions':{args:['-headless'],prefs:{'browser.shell.checkDefaultBrowser':false,'browser.download.folderList':2,'browser.download.dir':dir,'browser.download.useDownloadDir':true}}}}});sid=created.sessionId;
 await wd(`/session/${sid}/window/rect`,{width:1440,height:1000});await reset();
 pass('Démarrage, 6 groupes de genres, LLM absent',await js('return document.querySelectorAll(".genre-pills").length===6 && document.querySelector("#llm-wish").disabled'));
 await test('Atelier vide',async()=>{await panel('programme-builder');pass('Prérequis atelier vide',await js('return document.querySelector("#build-double").disabled && document.querySelector("#build-itinerary").disabled'));});
 await test('Filtres et 2 lentilles',async()=>{await checked('#lenses input[value="hidden-gem"]',true);await checked('#lenses input[value="elsewhere"]',true);pass('Maximum deux angles',await js('return document.querySelectorAll("#lenses input:disabled").length===2'));await checked('#lenses input[value="hidden-gem"]',false);pass('Déblocage angles',await js('return document.querySelectorAll("#lenses input:disabled").length===0'));await reset();});
 await test('Recherche et vues',async()=>{await search();pass('Programme quatre films', (await titles()).length===4,await titles());for(const v of ['catalogue','shortlist','programme']){await click(`[data-result-view="${v}"]`);pass(`Vue ${v}`,await js('return document.querySelector(arguments[0]).getAttribute("aria-pressed")==="true"',`[data-result-view="${v}"]`));}});
 await test('Remplacement une carte',async()=>{const before=await titles();await click('#movies article:first-child .studio-card-actions button:last-child');const after=await titles();pass('Remplacer la première conserve les 3 autres positions',before.slice(1).every((t,i)=>after[i+1]===t),{before,after});});
 await test('Verrouillage',async()=>{await click('#movies article:first-child .studio-card-actions button:nth-child(2)');const before=await titles();await click('#replace-programme');const after=await titles();pass('Verrou conservé',after.includes(before[0]),{before,after});});
 await test('Fiche, critiques, liens, avis',async()=>{await click('#movies article:first-child .studio-card-actions button:first-child');await wait('document.querySelector("#movie-drawer").open');await delay(200);pass('Fiche et disponibilité',await js('return document.querySelector("#drawer-body").textContent.includes("MUBI France")'));for(const aspect of ['director','theme','form','era','reception']){await value('#related-aspect',aspect);await click('#related-run');pass(`Explorer ${aspect}`,Boolean(await text('#related-results')));}await click('#taste-actions button:first-child');pass('Avis explicite sauvegardé',(await prefs()).history.length===1);await value('#movie-list','Ce soir');await click('#assign-list');pass('Liste Ce soir sauvegardée',Object.values((await prefs()).lists).includes('Ce soir'));await click('#close-drawer');pass('Fermeture fiche',await js('return !document.querySelector("#movie-drawer").open'));});
 await test('Bibliothèque et comparaison',async()=>{await click('#movies article:nth-child(2) [data-action="keep"]');await click('[data-result-view="shortlist"]');await checked('#shortlist-grid article:first-child input',true);await checked('#shortlist-grid article:nth-child(2) input',true);await click('#compare-shortlist');pass('Comparaison deux films',await js('return !document.querySelector("#comparison").hidden && document.querySelectorAll("#comparison thead th").length===3'));await value('#library-query','NO_RESULT_AUDIT');pass('Bibliothèque zéro résultat expliqué',/aucun/i.test(await text('#shortlist-grid')),await text('#shortlist-grid'));await value('#library-query','');await value('#library-list','Ce soir');pass('Filtre liste',await js('return document.querySelectorAll("#shortlist-grid article").length===1'));await value('#library-list','');});
 await test('Export',async()=>{await js('window.auditExport=null;const original=URL.createObjectURL;URL.createObjectURL=b=>{b.text().then(s=>window.auditExport=JSON.parse(s));return original(b)}');await click('#export-data');await wait('window.auditExport');pass('Export format et pas de clés',await js('return auditExport.format==="mubi-film-scout-local-v1" && !JSON.stringify(auditExport).includes("audit-fake-token")'));});
 await test('Profil',async()=>{await panel('profile-tool');await checked('#profile-veto input[value="53"]',true);await click('#save-profile');await checked('#use-profile',true);await click('#replace-programme');pass('Veto du profil respecté',await js('return !document.querySelector("#movies").textContent.includes("Genre principal TMDB : Thriller")'));await click('#reset-profile');await checked('#use-profile',false);pass('Réinitialisation du profil conserve avis',(await prefs()).history.length===1&&(await prefs()).profile.excludedGenres.length===0);});
 await test('Double séance, écho et duo',async()=>{await panel('programme-builder');await click('#build-double');pass('Double séance',await js('return document.querySelectorAll("#workshop-results article").length===2'));await value('#double-mode','echo');await click('#build-double');pass('Écho documenté',(await text('#workshop-results')).includes('friendship'));await panel('together-tool');await checked('#a-veto input[value="53"]',true);await checked('#b-likes input[value="35"]',true);await click('#choose-together');pass('Choix à deux',await js('return document.querySelectorAll("#workshop-results article").length>0'));await value('#together-budget','0');await click('#choose-together');pass('Durée zéro refusée pour duo',await js('return document.querySelectorAll("#workshop-results article").length===0'),(await text('#workshop-results')).slice(0,250));});
 await test('Collection fournie et parcours',async()=>{await panel('collections-tool');await click('#collection-seed');await wait('document.querySelectorAll("#collection-list button").length>0');pass('Collection fournie ajoutée',(await prefs()).collections.length===1);await click('#collection-list button:first-of-type');await wait('!document.querySelector("#collection-list button").disabled');await panel('programme-builder');await click('#build-itinerary');pass('Parcours 3 étapes',await js('return document.querySelectorAll("#workshop-results article").length===3'));});
 await test('Catalogue filtres et pagination',async()=>{await click('[data-result-view="catalogue"]');for(const s of ['rating','recent','oldest']){await value('#catalogue-sort',s);pass(`Tri ${s}`,await js('return document.querySelectorAll("#catalogue-grid article").length>0'));}await value('#catalogue-query','NO_RESULT_AUDIT');pass('Catalogue vide expliqué',/aucun/i.test(await text('#catalogue-progress')));await value('#catalogue-query','');await checked('#catalogue-verified',true);pass('Filtre vérifiés',await js('return document.querySelectorAll("#catalogue-grid article").length===document.querySelectorAll("#catalogue-grid .verified-badge").length'));await checked('#catalogue-verified',false);await click('#home-actions button:first-child');await wait('!document.querySelector("#catalogue-fetch-more").disabled');pass('Catalogue direct première page',await js('return document.querySelectorAll("#catalogue-grid article").length===20'));await click('.catalogue-footer-actions button:last-child');await wait('document.querySelectorAll("#catalogue-grid article").length>20');pass('Pagination deuxième page',await js('return document.querySelectorAll("#catalogue-grid article").length===40'));await value('#angle-filter','closed');pass('Angle filtre sans données',/aucun/i.test(await text('#catalogue-progress')));await value('#angle-filter','');});
 await test('Précision décodée et durée',async()=>{await reset();await value('#wish','science-fiction après 2010, moins de 100 minutes');await click('#parse-wish');await wait('!document.querySelector("#apply-language").hidden');await click('#apply-language');pass('Décodage appliqué',await js('return document.querySelector("#min-year").value==="2011" && [...document.querySelectorAll("#genres input:checked")].some(e=>e.value==="878")'));await checked('input[name="time-budget"][value="short"]',true);pass('Durée courte synchronisée',(await text('#active-criteria')).includes('90 min'),await text('#active-criteria'));});
 await test('Préréglage et annulation',async()=>{await reset();const before=await js('return document.querySelector("#min-year").value');await click('#oblique');await wait('!document.querySelector("#submit-search").disabled');await js('[...document.querySelectorAll("button")].find(e=>e.textContent==="Annuler le dernier préréglage").click()');pass('Annulation préréglage',await js('return document.querySelector("#min-year").value')===before);await click('#surprise');await wait('!document.querySelector("#submit-search").disabled');pass('Surprise produit un programme',(await titles()).length>0);});
 await test('Déjà vu et écarté',async()=>{await reset();await search();await click('#movies article:first-child [data-action="seen"]');pass('Vu stocké',(await prefs()).seen.length===1);await click('[data-result-view="catalogue"]');await click('#catalogue-grid article:first-child [data-action="dismiss"]');pass('Écarté stocké',(await prefs()).dismissed.length===1);await click('#restore-dismissed');pass('Restaurer écartés',(await prefs()).dismissed.length===0);});
 await test('Session écartée puis effacement',async()=>{await click('[data-result-view="programme"]');await click('#movies article:nth-child(2) .studio-card-actions button:first-child');await delay(150);await click('#reject-movie');pass('Rejet de session stocké',(await prefs()).rejections.length===1);await click('#forget');pass('Effacement des préférences',(await prefs()).seen.length===0&&(await prefs()).shortlist.length===0);const visible=await js('return !document.querySelector("#programme-tools").hidden');await click('#replace-programme');pass('Effacement ne ressuscite pas ancien programme',(await titles()).length===0,{controlsVisible:visible,titles:await titles()});});
 await test('Collection 30 films',async()=>{await reset();await panel('collections-tool');const payload={name:'Audit 30',films:Array.from({length:30},(_,i)=>({id:i+1,title:`Film ${i+1}`,order:i+1}))};await js('const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(arguments[0])],"audit.json",{type:"application/json"}));const e=document.querySelector("#collection-file");e.files=dt.files;e.dispatchEvent(new Event("change",{bubbles:true}));',payload);await wait('document.querySelectorAll("#collection-list button").length>0');await click('#collection-list button:first-of-type');await wait('!document.querySelector("#collection-list button").disabled');const n=await js('return document.querySelectorAll("#workshop-results article").length');pass('Collection permet accès aux 30 films',n===30,{accessible:n,expected:30});await click('#collection-list button:last-child');pass('Suppression collection de test',(await prefs()).collections.length===0);});
 await test('Import valide et persistance',async()=>{await reset();await search();await click('#movies article:first-child [data-action="keep"]');const p=await prefs();await reset();await js('const dt=new DataTransfer();dt.items.add(new File([JSON.stringify({format:"mubi-film-scout-local-v1",preferences:arguments[0]})],"audit-import.json",{type:"application/json"}));const e=document.querySelector("#import-file");e.files=dt.files;e.dispatchEvent(new Event("change",{bubbles:true}));',p);await wait('document.querySelectorAll("#shortlist-grid article").length===1');pass('Import valide rétablit la bibliothèque',(await prefs()).shortlist.length===1);await wd(`/session/${sid}/refresh`,{});await wait('document.querySelectorAll("#profile-like input").length===18');pass('Bibliothèque persistante après rechargement',await js('return document.querySelectorAll("#shortlist-grid article").length===1'));await panel('programme-builder');const enabled=await js('return !document.querySelector("#choose-together").disabled');await panel('together-tool');await click('#choose-together');const count=await js('return document.querySelectorAll("#workshop-results article").length');pass('Atelier utilise les films vérifiés annoncés',!enabled||count>0,{enabled,results:count,hint:await text('#workshop-hint')});await reset();});
 await test('Effacement pendant enrichissement',async()=>{await reset();await js('const original=window.fetch;window.fetch=async(...args)=>{const r=await original(...args);if(String(args[0]).includes("/api/enrich"))await new Promise(resolve=>setTimeout(resolve,1200));return r}');await search();await click('#forget');await delay(1600);pass('Réponse tardive ne restaure pas films effacés',(await titles()).length===0,await titles());});
 await test('Film devenu indisponible',async()=>{await reset();await js('const original=window.fetch;window.fetch=async(...args)=>{const r=await original(...args);if(String(args[0]).includes("/api/enrich")){const d=await r.json();d.movies=d.movies.map(m=>({...m,verified:false,availability:{...m.availability,available:false}}));return new Response(JSON.stringify(d),{status:200,headers:{"content-type":"application/json"}})}return r}');await search();pass('Programme retire disponibilité invalidée',(await titles()).length===0,await titles());});
 await test('Champs importés HTML',async()=>{await reset();const p={shortlist:[{id:1,title:'HTML probe',releaseDate:'2000-01-01',runtime:'<strong id="audit-injection">texte injecté</strong>',rating:8}]};await js('const dt=new DataTransfer();dt.items.add(new File([JSON.stringify({format:"mubi-film-scout-local-v1",preferences:arguments[0]})],"audit-html.json",{type:"application/json"}));const e=document.querySelector("#import-file");e.files=dt.files;e.dispatchEvent(new Event("change",{bubbles:true}));',p);await delay(200);pass('Import ne crée aucun balisage arbitraire',await js('return !document.querySelector("#audit-injection")'));});
 await test('Import invalide ne casse pas UI',async()=>{await reset();const payload={format:'mubi-film-scout-local-v1',preferences:{shortlist:[{id:1,title:'Bad import',releaseDate:2020,runtime:90,rating:'8.1'}]}};await js('const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(arguments[0])],"audit-bad.json",{type:"application/json"}));const e=document.querySelector("#import-file");e.files=dt.files;e.dispatchEvent(new Event("change",{bubbles:true}));',payload);await delay(200);await wd(`/session/${sid}/refresh`,{});await delay(500);pass('Import types invalides ne bloque pas démarrage',await js('return document.querySelectorAll("#profile-like input").length===18'),await text('#status'));});
 await test('Sources fictives dans coffre isolé',async()=>{await reset();await value('#guardian-key','audit-fake-guardian');await click('#save-sources');await wait('!document.querySelector("#save-sources").disabled');pass('Clé fictive enregistrée sans réaffichage',await js('return document.querySelector("#guardian-key").value===""'));await click('#clear-sources');await wait('!document.querySelector("#clear-sources").disabled');const s=await fetch(base+'/api/status').then(r=>r.json());pass('Effacer coffre conserve jeton environnement',s.connections.tmdb.configured&&!s.connections.guardian.configured);await click('#run-diagnostic');await wait('!document.querySelector("#run-diagnostic").disabled');pass('Diagnostic fictif fonctionne',(await text('#diagnostic-tmdb')).length>0);});
 await reset();await search();
 await test('Responsive et clavier',async()=>{for(const width of [1440,768,500]){await wd(`/session/${sid}/window/rect`,{width,height:900});pass(`Pas de débordement ${width}`,await js('return document.documentElement.scrollWidth<=innerWidth'),await js('return {width:innerWidth,scroll:document.documentElement.scrollWidth}'));}await click('#movies article:first-child .studio-card-actions button:first-child');await delay(200);await wd(`/session/${sid}/actions`,{actions:[{type:'key',id:'keyboard',actions:[{type:'keyDown',value:'\uE00C'},{type:'keyUp',value:'\uE00C'}]}]});pass('Échap ferme la fiche',await js('return !document.querySelector("#movie-drawer").open'));const png=await wd(`/session/${sid}/screenshot`);await writeFile(`${dir}/mobile.png`,Buffer.from(png,'base64'));});
 await test('HTTP sécurité et entrées invalides',async()=>{for(const [path,body,expected] of [['/api/interpret','{',400],['/api/movie',{id:-1},400],['/api/enrich',{ids:[1,2,3,4,5]},400],['/api/language',{text:'film'},428],['/api/interpret',{wish:'x'.repeat(65000)},413]]){const r=await post(path,body);pass(`${path} ${expected}`,r.status===expected,r.status);}for(const header of [{Origin:'https://evil.invalid'},{Host:'evil.invalid'}]){const status=await new Promise((resolve,reject)=>{const r=http.request(base+'/api/interpret',{method:'POST',headers:{...header,'content-type':'application/json'}},res=>{res.resume();resolve(res.statusCode)});r.on('error',reject);r.end('{}')});pass(`Refus ${Object.keys(header)[0]}`,status===403,status);}const r=await fetch(base+'/.sources.local.json');pass('Coffre inaccessible HTTP',r.status===404,r.status);});
 await test('Page en panne reste rechargeable',async()=>{failPages.add(2);const r=await fetch(base+'/api/search',{method:'POST',headers:{'content-type':'application/json','x-tmdb-token':'audit-fresh-page-failure'},body:JSON.stringify({progressive:true,filters:{effect:'open',minYear:1990,maxYear:2026,maxRuntime:180}})});const d=await r.json();pass('Page échouée non déclarée chargée',!d.exploredPages.includes(2),{pages:d.exploredPages,warnings:d.warnings});failPages.clear();});
 await test('Repli anti-série',async()=>{const {tooSimilar}=await import(pathToFileURL(project+'/public/discovery.mjs'));const a={id:1,title:'American Alpha',genreIds:[18]},b={id:2,title:'American Beta',genreIds:[18]};pass('Premier mot seul ne prouve pas une série',!tooSimilar(a,b),{a:a.title,b:b.title,tooSimilar:tooSimilar(a,b)});});
 await test('Sauvegardes concurrentes du coffre fictif',async()=>{const {createConnectionStore}=await import(pathToFileURL(project+'/lib/connections.mjs'));for(let i=0;i<3;i++){const store=createConnectionStore(`${dir}/parallel-${i}.json`);const r=await Promise.allSettled([store.save({guardian:'fake-guardian'}),store.save({nyt:'fake-nyt'})]);let state;try{state=await store.status()}catch(e){state={error:e.message}}pass(`Coffre concurrence ${i+1}`,r.every(x=>x.status==='fulfilled')&&state.guardian?.configured&&state.nyt?.configured,{results:r.map(x=>({status:x.status,error:x.reason?.code||x.reason?.message})),state});}});
 await test('Lots suivants et affichage progressif collection 80 films',async()=>{
  await reset(); await panel('collections-tool');
  const payload={name:'Audit 80',films:Array.from({length:80},(_,i)=>({id:i+1,title:`Film ${i+1}`,order:i+1}))};
  await js('const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(arguments[0])],"audit.json",{type:"application/json"}));const e=document.querySelector("#collection-file");e.files=dt.files;e.dispatchEvent(new Event("change",{bubbles:true}));',payload);
  await wait('document.querySelectorAll("#collection-list button").length>0');
  await click('#collection-list button:first-of-type'); await wait('document.querySelector("#collection-list button").textContent.includes("20/80")');
  await click('#collection-list button:first-of-type'); await wait('document.querySelector("#collection-list button").textContent.includes("40/80")');
  pass('Second lot de collection distinct et accessible',(await text('#collection-list button')).includes('40/80'),await text('#collection-list button'));
  await click('#workshop-results .mini-more');
  pass('Affichage des 80 films sans plafond caché',await js('return document.querySelectorAll("#workshop-results article").length===80'));
 });
 console.log('ARTIFACT_DIR='+dir);
}finally{
 await writeFile(`${dir}/results.json`,JSON.stringify(findings,null,2));
 if(sid)await wd(`/session/${sid}`,undefined,'DELETE').catch(()=>{});
 app?.kill('SIGTERM');source.close();
 console.log(JSON.stringify({total:findings.length,pass:findings.filter(f=>f.status==='PASS').length,fail:findings.filter(f=>f.status==='FAIL').length,error:findings.filter(f=>f.status==='ERROR').length,dir}));
 if(findings.some(f=>f.status!=='PASS'))process.exitCode=1;
}
